-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matrix_mult is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    A_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_ce0 : OUT STD_LOGIC;
    A_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    B_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    B_ce0 : OUT STD_LOGIC;
    B_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    C_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    C_ce0 : OUT STD_LOGIC;
    C_we0 : OUT STD_LOGIC;
    C_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of matrix_mult is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matrix_mult,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu13p-fsga2577-2-e,HLS_INPUT_CLOCK=25.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.208000,HLS_SYN_LAT=2221,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=3,HLS_SYN_FF=79,HLS_SYN_LUT=274,HLS_VERSION=2020_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal i_fu_124_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_reg_267 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln10_1_fu_154_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln10_1_reg_272 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln6_fu_118_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_fu_166_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal j_reg_281 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal zext_ln8_fu_172_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln8_reg_286 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln7_fu_160_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal C_addr_reg_291 : STD_LOGIC_VECTOR (6 downto 0);
    signal k_fu_192_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal k_reg_299 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln9_fu_186_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln10_fu_258_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal i_0_reg_72 : STD_LOGIC_VECTOR (3 downto 0);
    signal j_0_reg_83 : STD_LOGIC_VECTOR (3 downto 0);
    signal C_load_reg_94 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_0_reg_107 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln8_1_fu_181_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln10_3_fu_207_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln10_6_fu_247_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_fu_130_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_1_fu_142_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln10_1_fu_150_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln10_fu_138_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln8_fu_176_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln10_2_fu_198_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln10_2_fu_202_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_212_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_3_fu_224_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln10_5_fu_232_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln10_4_fu_220_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln10_3_fu_236_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln10_4_fu_242_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln10_fu_252_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln10_fu_252_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln10_fu_252_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    C_load_reg_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                C_load_reg_94 <= add_ln10_fu_258_p2;
            elsif (((icmp_ln7_fu_160_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                C_load_reg_94 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    i_0_reg_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln7_fu_160_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_0_reg_72 <= i_reg_267;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_0_reg_72 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    j_0_reg_83_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln9_fu_186_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                j_0_reg_83 <= j_reg_281;
            elsif (((icmp_ln6_fu_118_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                j_0_reg_83 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    k_0_reg_107_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                k_0_reg_107 <= k_reg_299;
            elsif (((icmp_ln7_fu_160_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                k_0_reg_107 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln7_fu_160_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                C_addr_reg_291 <= zext_ln8_1_fu_181_p1(7 - 1 downto 0);
                    zext_ln8_reg_286(3 downto 0) <= zext_ln8_fu_172_p1(3 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln6_fu_118_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    add_ln10_1_reg_272(7 downto 1) <= add_ln10_1_fu_154_p2(7 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_reg_267 <= i_fu_124_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                j_reg_281 <= j_fu_166_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                k_reg_299 <= k_fu_192_p2;
            end if;
        end if;
    end process;
    add_ln10_1_reg_272(0) <= '0';
    zext_ln8_reg_286(7 downto 4) <= "0000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln6_fu_118_p2, ap_CS_fsm_state3, icmp_ln7_fu_160_p2, ap_CS_fsm_state4, icmp_ln9_fu_186_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln6_fu_118_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln7_fu_160_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln9_fu_186_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    A_address0 <= zext_ln10_3_fu_207_p1(7 - 1 downto 0);

    A_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            A_ce0 <= ap_const_logic_1;
        else 
            A_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    B_address0 <= zext_ln10_6_fu_247_p1(7 - 1 downto 0);

    B_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            B_ce0 <= ap_const_logic_1;
        else 
            B_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    C_address0 <= C_addr_reg_291;

    C_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            C_ce0 <= ap_const_logic_1;
        else 
            C_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    C_d0 <= C_load_reg_94;

    C_we0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            C_we0 <= ap_const_logic_1;
        else 
            C_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln10_1_fu_154_p2 <= std_logic_vector(unsigned(zext_ln10_1_fu_150_p1) + unsigned(zext_ln10_fu_138_p1));
    add_ln10_2_fu_202_p2 <= std_logic_vector(unsigned(add_ln10_1_reg_272) + unsigned(zext_ln10_2_fu_198_p1));
    add_ln10_3_fu_236_p2 <= std_logic_vector(unsigned(zext_ln10_5_fu_232_p1) + unsigned(zext_ln10_4_fu_220_p1));
    add_ln10_4_fu_242_p2 <= std_logic_vector(unsigned(add_ln10_3_fu_236_p2) + unsigned(zext_ln8_reg_286));
    add_ln10_fu_258_p2 <= std_logic_vector(unsigned(mul_ln10_fu_252_p2) + unsigned(C_load_reg_94));
    add_ln8_fu_176_p2 <= std_logic_vector(unsigned(add_ln10_1_reg_272) + unsigned(zext_ln8_fu_172_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_done_assign_proc : process(ap_CS_fsm_state2, icmp_ln6_fu_118_p2)
    begin
        if (((icmp_ln6_fu_118_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln6_fu_118_p2)
    begin
        if (((icmp_ln6_fu_118_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    i_fu_124_p2 <= std_logic_vector(unsigned(i_0_reg_72) + unsigned(ap_const_lv4_1));
    icmp_ln6_fu_118_p2 <= "1" when (i_0_reg_72 = ap_const_lv4_A) else "0";
    icmp_ln7_fu_160_p2 <= "1" when (j_0_reg_83 = ap_const_lv4_A) else "0";
    icmp_ln9_fu_186_p2 <= "1" when (k_0_reg_107 = ap_const_lv4_A) else "0";
    j_fu_166_p2 <= std_logic_vector(unsigned(j_0_reg_83) + unsigned(ap_const_lv4_1));
    k_fu_192_p2 <= std_logic_vector(unsigned(k_0_reg_107) + unsigned(ap_const_lv4_1));
    mul_ln10_fu_252_p0 <= B_q0;
    mul_ln10_fu_252_p1 <= A_q0;
    mul_ln10_fu_252_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln10_fu_252_p0) * signed(mul_ln10_fu_252_p1))), 32));
    tmp_1_fu_142_p3 <= (i_0_reg_72 & ap_const_lv1_0);
    tmp_2_fu_212_p3 <= (k_0_reg_107 & ap_const_lv3_0);
    tmp_3_fu_224_p3 <= (k_0_reg_107 & ap_const_lv1_0);
    tmp_fu_130_p3 <= (i_0_reg_72 & ap_const_lv3_0);
    zext_ln10_1_fu_150_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_142_p3),8));
    zext_ln10_2_fu_198_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_0_reg_107),8));
    zext_ln10_3_fu_207_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln10_2_fu_202_p2),64));
    zext_ln10_4_fu_220_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_212_p3),8));
    zext_ln10_5_fu_232_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_224_p3),8));
    zext_ln10_6_fu_247_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln10_4_fu_242_p2),64));
    zext_ln10_fu_138_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_130_p3),8));
    zext_ln8_1_fu_181_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln8_fu_176_p2),64));
    zext_ln8_fu_172_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_0_reg_83),8));
end behav;
