// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module sorter_sorter_Pipeline_VITIS_LOOP_6_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        indvars_iv6,
        a_address0,
        a_ce0,
        a_we0,
        a_d0,
        a_q0,
        a_address1,
        a_ce1,
        a_we1,
        a_d1,
        a_q1
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [3:0] indvars_iv6;
output  [3:0] a_address0;
output   a_ce0;
output   a_we0;
output  [31:0] a_d0;
input  [31:0] a_q0;
output  [3:0] a_address1;
output   a_ce1;
output   a_we1;
output  [31:0] a_d1;
input  [31:0] a_q1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln6_fu_83_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_state2;
wire   [3:0] add_ln7_fu_89_p2;
reg   [3:0] add_ln7_reg_125;
reg   [3:0] a_addr_reg_130;
reg   [3:0] a_addr_1_reg_135;
wire   [63:0] zext_ln6_fu_95_p1;
wire   [63:0] zext_ln7_fu_100_p1;
reg   [3:0] j_fu_38;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_j_1;
reg    a_ce1_local;
reg   [3:0] a_address1_local;
reg    a_ce0_local;
reg   [3:0] a_address0_local;
reg    a_we1_local;
wire   [0:0] icmp_ln7_fu_105_p2;
reg    a_we0_local;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 j_fu_38 = 4'd0;
#0 ap_done_reg = 1'b0;
end

sorter_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        j_fu_38 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        j_fu_38 <= add_ln7_reg_125;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        a_addr_1_reg_135 <= zext_ln7_fu_100_p1;
        a_addr_reg_130 <= zext_ln6_fu_95_p1;
        add_ln7_reg_125 <= add_ln7_fu_89_p2;
    end
end

always @ (*) begin
    if (((icmp_ln7_fu_105_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        a_address0_local = a_addr_1_reg_135;
    end else if (((icmp_ln6_fu_83_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        a_address0_local = zext_ln7_fu_100_p1;
    end else begin
        a_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln7_fu_105_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        a_address1_local = a_addr_reg_130;
    end else if (((icmp_ln6_fu_83_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        a_address1_local = zext_ln6_fu_95_p1;
    end else begin
        a_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln7_fu_105_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln6_fu_83_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)))) begin
        a_ce0_local = 1'b1;
    end else begin
        a_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln7_fu_105_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln6_fu_83_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)))) begin
        a_ce1_local = 1'b1;
    end else begin
        a_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln7_fu_105_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        a_we0_local = 1'b1;
    end else begin
        a_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln7_fu_105_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        a_we1_local = 1'b1;
    end else begin
        a_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln6_fu_83_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_j_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_38;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln6_fu_83_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_address0 = a_address0_local;

assign a_address1 = a_address1_local;

assign a_ce0 = a_ce0_local;

assign a_ce1 = a_ce1_local;

assign a_d0 = a_q1;

assign a_d1 = a_q0;

assign a_we0 = a_we0_local;

assign a_we1 = a_we1_local;

assign add_ln7_fu_89_p2 = (ap_sig_allocacmp_j_1 + 4'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln6_fu_83_p2 = ((ap_sig_allocacmp_j_1 == indvars_iv6) ? 1'b1 : 1'b0);

assign icmp_ln7_fu_105_p2 = (($signed(a_q1) > $signed(a_q0)) ? 1'b1 : 1'b0);

assign zext_ln6_fu_95_p1 = ap_sig_allocacmp_j_1;

assign zext_ln7_fu_100_p1 = add_ln7_fu_89_p2;

endmodule //sorter_sorter_Pipeline_VITIS_LOOP_6_2
