// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="vec_add_vec_add,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu13p-fsga2577-2-e,HLS_INPUT_CLOCK=25.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.151000,HLS_SYN_LAT=8,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=9,HLS_SYN_LUT=376,HLS_VERSION=2024_1}" *)

module vec_add (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_address0,
        A_ce0,
        A_q0,
        A_address1,
        A_ce1,
        A_q1,
        B_address0,
        B_ce0,
        B_q0,
        B_address1,
        B_ce1,
        B_q1,
        C_address0,
        C_ce0,
        C_we0,
        C_d0,
        C_address1,
        C_ce1,
        C_we1,
        C_d1
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] A_address0;
output   A_ce0;
input  [15:0] A_q0;
output  [3:0] A_address1;
output   A_ce1;
input  [15:0] A_q1;
output  [3:0] B_address0;
output   B_ce0;
input  [15:0] B_q0;
output  [3:0] B_address1;
output   B_ce1;
input  [15:0] B_q1;
output  [3:0] C_address0;
output   C_ce0;
output   C_we0;
output  [15:0] C_d0;
output  [3:0] C_address1;
output   C_ce1;
output   C_we1;
output  [15:0] C_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg    A_ce1_local;
reg   [3:0] A_address1_local;
reg    A_ce0_local;
reg   [3:0] A_address0_local;
reg    B_ce1_local;
reg   [3:0] B_address1_local;
reg    B_ce0_local;
reg   [3:0] B_address0_local;
reg    C_we1_local;
wire   [15:0] grp_fu_484_p2;
reg    C_ce1_local;
reg   [3:0] C_address1_local;
reg    C_we0_local;
wire   [15:0] grp_fu_491_p2;
reg    C_ce0_local;
reg   [3:0] C_address0_local;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        A_address0_local = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        A_address0_local = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        A_address0_local = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        A_address0_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        A_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        A_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        A_address0_local = 64'd1;
    end else begin
        A_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        A_address1_local = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        A_address1_local = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        A_address1_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        A_address1_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        A_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        A_address1_local = 64'd0;
    end else begin
        A_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        A_ce0_local = 1'b1;
    end else begin
        A_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        A_ce1_local = 1'b1;
    end else begin
        A_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        B_address0_local = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        B_address0_local = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_address0_local = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        B_address0_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        B_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        B_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        B_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        B_address0_local = 64'd1;
    end else begin
        B_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        B_address1_local = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_address1_local = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        B_address1_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        B_address1_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        B_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        B_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        B_address1_local = 64'd0;
    end else begin
        B_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        B_ce0_local = 1'b1;
    end else begin
        B_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        B_ce1_local = 1'b1;
    end else begin
        B_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        C_address0_local = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        C_address0_local = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        C_address0_local = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        C_address0_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        C_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        C_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        C_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        C_address0_local = 64'd1;
    end else begin
        C_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        C_address1_local = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        C_address1_local = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        C_address1_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        C_address1_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        C_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        C_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        C_address1_local = 64'd0;
    end else begin
        C_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        C_ce0_local = 1'b1;
    end else begin
        C_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        C_ce1_local = 1'b1;
    end else begin
        C_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        C_we0_local = 1'b1;
    end else begin
        C_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        C_we1_local = 1'b1;
    end else begin
        C_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_address0 = A_address0_local;

assign A_address1 = A_address1_local;

assign A_ce0 = A_ce0_local;

assign A_ce1 = A_ce1_local;

assign B_address0 = B_address0_local;

assign B_address1 = B_address1_local;

assign B_ce0 = B_ce0_local;

assign B_ce1 = B_ce1_local;

assign C_address0 = C_address0_local;

assign C_address1 = C_address1_local;

assign C_ce0 = C_ce0_local;

assign C_ce1 = C_ce1_local;

assign C_d0 = grp_fu_491_p2;

assign C_d1 = grp_fu_484_p2;

assign C_we0 = C_we0_local;

assign C_we1 = C_we1_local;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_fu_484_p2 = (B_q1 + A_q1);

assign grp_fu_491_p2 = (B_q0 + A_q0);

endmodule //vec_add
