-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hw5_ex1_op is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    A_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_EN_A : OUT STD_LOGIC;
    A_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    A_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    A_Clk_A : OUT STD_LOGIC;
    A_Rst_A : OUT STD_LOGIC;
    B_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_EN_A : OUT STD_LOGIC;
    B_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    B_Clk_A : OUT STD_LOGIC;
    B_Rst_A : OUT STD_LOGIC );
end;


architecture behav of hw5_ex1_op is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "hw5_ex1_op_hw5_ex1_op,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu13p-fsga2577-2-e,HLS_INPUT_CLOCK=25.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.913812,HLS_SYN_LAT=108,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=441,HLS_SYN_LUT=1155,HLS_VERSION=2024_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal temp1_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal temp1_ce0 : STD_LOGIC;
    signal temp1_we0 : STD_LOGIC;
    signal temp1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal temp1_1_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal temp1_1_ce0 : STD_LOGIC;
    signal temp1_1_we0 : STD_LOGIC;
    signal temp1_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal temp1_2_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal temp1_2_ce0 : STD_LOGIC;
    signal temp1_2_we0 : STD_LOGIC;
    signal temp1_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal temp2_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal temp2_ce0 : STD_LOGIC;
    signal temp2_we0 : STD_LOGIC;
    signal temp2_q0 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_read_data_fu_44_ap_start : STD_LOGIC;
    signal grp_read_data_fu_44_ap_done : STD_LOGIC;
    signal grp_read_data_fu_44_ap_idle : STD_LOGIC;
    signal grp_read_data_fu_44_ap_ready : STD_LOGIC;
    signal grp_read_data_fu_44_A_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_read_data_fu_44_A_EN_A : STD_LOGIC;
    signal grp_read_data_fu_44_A_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_data_fu_44_A_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_read_data_fu_44_out_r_0_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_data_fu_44_out_r_0_ce0 : STD_LOGIC;
    signal grp_read_data_fu_44_out_r_0_we0 : STD_LOGIC;
    signal grp_read_data_fu_44_out_r_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_read_data_fu_44_out_r_1_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_data_fu_44_out_r_1_ce0 : STD_LOGIC;
    signal grp_read_data_fu_44_out_r_1_we0 : STD_LOGIC;
    signal grp_read_data_fu_44_out_r_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_read_data_fu_44_out_r_2_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_data_fu_44_out_r_2_ce0 : STD_LOGIC;
    signal grp_read_data_fu_44_out_r_2_we0 : STD_LOGIC;
    signal grp_read_data_fu_44_out_r_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_compute_blur_fu_56_ap_start : STD_LOGIC;
    signal grp_compute_blur_fu_56_ap_done : STD_LOGIC;
    signal grp_compute_blur_fu_56_ap_idle : STD_LOGIC;
    signal grp_compute_blur_fu_56_ap_ready : STD_LOGIC;
    signal grp_compute_blur_fu_56_in_c_0_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_compute_blur_fu_56_in_c_0_ce0 : STD_LOGIC;
    signal grp_compute_blur_fu_56_in_c_1_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_compute_blur_fu_56_in_c_1_ce0 : STD_LOGIC;
    signal grp_compute_blur_fu_56_in_c_2_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_compute_blur_fu_56_in_c_2_ce0 : STD_LOGIC;
    signal grp_compute_blur_fu_56_out_c_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_compute_blur_fu_56_out_c_ce0 : STD_LOGIC;
    signal grp_compute_blur_fu_56_out_c_we0 : STD_LOGIC;
    signal grp_compute_blur_fu_56_out_c_d0 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_write_data_fu_64_ap_start : STD_LOGIC;
    signal grp_write_data_fu_64_ap_done : STD_LOGIC;
    signal grp_write_data_fu_64_ap_idle : STD_LOGIC;
    signal grp_write_data_fu_64_ap_ready : STD_LOGIC;
    signal grp_write_data_fu_64_in_w_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_write_data_fu_64_in_w_ce0 : STD_LOGIC;
    signal grp_write_data_fu_64_B_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_write_data_fu_64_B_EN_A : STD_LOGIC;
    signal grp_write_data_fu_64_B_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_data_fu_64_B_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_read_data_fu_44_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_compute_blur_fu_56_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_write_data_fu_64_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component hw5_ex1_op_read_data IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        A_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        A_EN_A : OUT STD_LOGIC;
        A_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        A_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        A_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
        out_r_0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_r_0_ce0 : OUT STD_LOGIC;
        out_r_0_we0 : OUT STD_LOGIC;
        out_r_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_r_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_r_1_ce0 : OUT STD_LOGIC;
        out_r_1_we0 : OUT STD_LOGIC;
        out_r_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_r_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_r_2_ce0 : OUT STD_LOGIC;
        out_r_2_we0 : OUT STD_LOGIC;
        out_r_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component hw5_ex1_op_compute_blur IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_c_0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        in_c_0_ce0 : OUT STD_LOGIC;
        in_c_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_c_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        in_c_1_ce0 : OUT STD_LOGIC;
        in_c_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_c_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        in_c_2_ce0 : OUT STD_LOGIC;
        in_c_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_c_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        out_c_ce0 : OUT STD_LOGIC;
        out_c_we0 : OUT STD_LOGIC;
        out_c_d0 : OUT STD_LOGIC_VECTOR (30 downto 0) );
    end component;


    component hw5_ex1_op_write_data IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_w_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        in_w_ce0 : OUT STD_LOGIC;
        in_w_q0 : IN STD_LOGIC_VECTOR (30 downto 0);
        B_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        B_EN_A : OUT STD_LOGIC;
        B_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        B_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        B_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component hw5_ex1_op_temp1_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component hw5_ex1_op_temp2_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (30 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (30 downto 0) );
    end component;



begin
    temp1_U : component hw5_ex1_op_temp1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => temp1_address0,
        ce0 => temp1_ce0,
        we0 => temp1_we0,
        d0 => grp_read_data_fu_44_out_r_0_d0,
        q0 => temp1_q0);

    temp1_1_U : component hw5_ex1_op_temp1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => temp1_1_address0,
        ce0 => temp1_1_ce0,
        we0 => temp1_1_we0,
        d0 => grp_read_data_fu_44_out_r_1_d0,
        q0 => temp1_1_q0);

    temp1_2_U : component hw5_ex1_op_temp1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => temp1_2_address0,
        ce0 => temp1_2_ce0,
        we0 => temp1_2_we0,
        d0 => grp_read_data_fu_44_out_r_2_d0,
        q0 => temp1_2_q0);

    temp2_U : component hw5_ex1_op_temp2_RAM_AUTO_1R1W
    generic map (
        DataWidth => 31,
        AddressRange => 30,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => temp2_address0,
        ce0 => temp2_ce0,
        we0 => temp2_we0,
        d0 => grp_compute_blur_fu_56_out_c_d0,
        q0 => temp2_q0);

    grp_read_data_fu_44 : component hw5_ex1_op_read_data
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_read_data_fu_44_ap_start,
        ap_done => grp_read_data_fu_44_ap_done,
        ap_idle => grp_read_data_fu_44_ap_idle,
        ap_ready => grp_read_data_fu_44_ap_ready,
        A_Addr_A => grp_read_data_fu_44_A_Addr_A,
        A_EN_A => grp_read_data_fu_44_A_EN_A,
        A_WEN_A => grp_read_data_fu_44_A_WEN_A,
        A_Din_A => grp_read_data_fu_44_A_Din_A,
        A_Dout_A => A_Dout_A,
        out_r_0_address0 => grp_read_data_fu_44_out_r_0_address0,
        out_r_0_ce0 => grp_read_data_fu_44_out_r_0_ce0,
        out_r_0_we0 => grp_read_data_fu_44_out_r_0_we0,
        out_r_0_d0 => grp_read_data_fu_44_out_r_0_d0,
        out_r_1_address0 => grp_read_data_fu_44_out_r_1_address0,
        out_r_1_ce0 => grp_read_data_fu_44_out_r_1_ce0,
        out_r_1_we0 => grp_read_data_fu_44_out_r_1_we0,
        out_r_1_d0 => grp_read_data_fu_44_out_r_1_d0,
        out_r_2_address0 => grp_read_data_fu_44_out_r_2_address0,
        out_r_2_ce0 => grp_read_data_fu_44_out_r_2_ce0,
        out_r_2_we0 => grp_read_data_fu_44_out_r_2_we0,
        out_r_2_d0 => grp_read_data_fu_44_out_r_2_d0);

    grp_compute_blur_fu_56 : component hw5_ex1_op_compute_blur
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_compute_blur_fu_56_ap_start,
        ap_done => grp_compute_blur_fu_56_ap_done,
        ap_idle => grp_compute_blur_fu_56_ap_idle,
        ap_ready => grp_compute_blur_fu_56_ap_ready,
        in_c_0_address0 => grp_compute_blur_fu_56_in_c_0_address0,
        in_c_0_ce0 => grp_compute_blur_fu_56_in_c_0_ce0,
        in_c_0_q0 => temp1_q0,
        in_c_1_address0 => grp_compute_blur_fu_56_in_c_1_address0,
        in_c_1_ce0 => grp_compute_blur_fu_56_in_c_1_ce0,
        in_c_1_q0 => temp1_1_q0,
        in_c_2_address0 => grp_compute_blur_fu_56_in_c_2_address0,
        in_c_2_ce0 => grp_compute_blur_fu_56_in_c_2_ce0,
        in_c_2_q0 => temp1_2_q0,
        out_c_address0 => grp_compute_blur_fu_56_out_c_address0,
        out_c_ce0 => grp_compute_blur_fu_56_out_c_ce0,
        out_c_we0 => grp_compute_blur_fu_56_out_c_we0,
        out_c_d0 => grp_compute_blur_fu_56_out_c_d0);

    grp_write_data_fu_64 : component hw5_ex1_op_write_data
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_write_data_fu_64_ap_start,
        ap_done => grp_write_data_fu_64_ap_done,
        ap_idle => grp_write_data_fu_64_ap_idle,
        ap_ready => grp_write_data_fu_64_ap_ready,
        in_w_address0 => grp_write_data_fu_64_in_w_address0,
        in_w_ce0 => grp_write_data_fu_64_in_w_ce0,
        in_w_q0 => temp2_q0,
        B_Addr_A => grp_write_data_fu_64_B_Addr_A,
        B_EN_A => grp_write_data_fu_64_B_EN_A,
        B_WEN_A => grp_write_data_fu_64_B_WEN_A,
        B_Din_A => grp_write_data_fu_64_B_Din_A,
        B_Dout_A => ap_const_lv32_0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_compute_blur_fu_56_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_compute_blur_fu_56_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_compute_blur_fu_56_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_compute_blur_fu_56_ap_ready = ap_const_logic_1)) then 
                    grp_compute_blur_fu_56_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_read_data_fu_44_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_read_data_fu_44_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_read_data_fu_44_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_read_data_fu_44_ap_ready = ap_const_logic_1)) then 
                    grp_read_data_fu_44_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_write_data_fu_64_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_write_data_fu_64_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_write_data_fu_64_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_write_data_fu_64_ap_ready = ap_const_logic_1)) then 
                    grp_write_data_fu_64_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_read_data_fu_44_ap_done, grp_compute_blur_fu_56_ap_done, grp_write_data_fu_64_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_read_data_fu_44_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_compute_blur_fu_56_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_write_data_fu_64_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    A_Addr_A <= grp_read_data_fu_44_A_Addr_A;
    A_Clk_A <= ap_clk;
    A_Din_A <= ap_const_lv32_0;
    A_EN_A <= grp_read_data_fu_44_A_EN_A;
    A_Rst_A <= ap_rst;
    A_WEN_A <= ap_const_lv4_0;
    B_Addr_A <= grp_write_data_fu_64_B_Addr_A;
    B_Clk_A <= ap_clk;
    B_Din_A <= grp_write_data_fu_64_B_Din_A;
    B_EN_A <= grp_write_data_fu_64_B_EN_A;
    B_Rst_A <= ap_rst;
    B_WEN_A <= grp_write_data_fu_64_B_WEN_A;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_read_data_fu_44_ap_done)
    begin
        if ((grp_read_data_fu_44_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_compute_blur_fu_56_ap_done)
    begin
        if ((grp_compute_blur_fu_56_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_write_data_fu_64_ap_done)
    begin
        if ((grp_write_data_fu_64_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(grp_write_data_fu_64_ap_done, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_write_data_fu_64_ap_done = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_write_data_fu_64_ap_done, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_write_data_fu_64_ap_done = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_compute_blur_fu_56_ap_start <= grp_compute_blur_fu_56_ap_start_reg;
    grp_read_data_fu_44_ap_start <= grp_read_data_fu_44_ap_start_reg;
    grp_write_data_fu_64_ap_start <= grp_write_data_fu_64_ap_start_reg;

    temp1_1_address0_assign_proc : process(grp_read_data_fu_44_out_r_1_address0, grp_compute_blur_fu_56_in_c_1_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            temp1_1_address0 <= grp_compute_blur_fu_56_in_c_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            temp1_1_address0 <= grp_read_data_fu_44_out_r_1_address0;
        else 
            temp1_1_address0 <= "XXXX";
        end if; 
    end process;


    temp1_1_ce0_assign_proc : process(grp_read_data_fu_44_out_r_1_ce0, grp_compute_blur_fu_56_in_c_1_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            temp1_1_ce0 <= grp_compute_blur_fu_56_in_c_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            temp1_1_ce0 <= grp_read_data_fu_44_out_r_1_ce0;
        else 
            temp1_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    temp1_1_we0_assign_proc : process(grp_read_data_fu_44_out_r_1_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            temp1_1_we0 <= grp_read_data_fu_44_out_r_1_we0;
        else 
            temp1_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    temp1_2_address0_assign_proc : process(grp_read_data_fu_44_out_r_2_address0, grp_compute_blur_fu_56_in_c_2_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            temp1_2_address0 <= grp_compute_blur_fu_56_in_c_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            temp1_2_address0 <= grp_read_data_fu_44_out_r_2_address0;
        else 
            temp1_2_address0 <= "XXXX";
        end if; 
    end process;


    temp1_2_ce0_assign_proc : process(grp_read_data_fu_44_out_r_2_ce0, grp_compute_blur_fu_56_in_c_2_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            temp1_2_ce0 <= grp_compute_blur_fu_56_in_c_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            temp1_2_ce0 <= grp_read_data_fu_44_out_r_2_ce0;
        else 
            temp1_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    temp1_2_we0_assign_proc : process(grp_read_data_fu_44_out_r_2_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            temp1_2_we0 <= grp_read_data_fu_44_out_r_2_we0;
        else 
            temp1_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    temp1_address0_assign_proc : process(grp_read_data_fu_44_out_r_0_address0, grp_compute_blur_fu_56_in_c_0_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            temp1_address0 <= grp_compute_blur_fu_56_in_c_0_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            temp1_address0 <= grp_read_data_fu_44_out_r_0_address0;
        else 
            temp1_address0 <= "XXXX";
        end if; 
    end process;


    temp1_ce0_assign_proc : process(grp_read_data_fu_44_out_r_0_ce0, grp_compute_blur_fu_56_in_c_0_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            temp1_ce0 <= grp_compute_blur_fu_56_in_c_0_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            temp1_ce0 <= grp_read_data_fu_44_out_r_0_ce0;
        else 
            temp1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    temp1_we0_assign_proc : process(grp_read_data_fu_44_out_r_0_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            temp1_we0 <= grp_read_data_fu_44_out_r_0_we0;
        else 
            temp1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    temp2_address0_assign_proc : process(grp_compute_blur_fu_56_out_c_address0, grp_write_data_fu_64_in_w_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            temp2_address0 <= grp_write_data_fu_64_in_w_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            temp2_address0 <= grp_compute_blur_fu_56_out_c_address0;
        else 
            temp2_address0 <= "XXXXX";
        end if; 
    end process;


    temp2_ce0_assign_proc : process(grp_compute_blur_fu_56_out_c_ce0, grp_write_data_fu_64_in_w_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            temp2_ce0 <= grp_write_data_fu_64_in_w_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            temp2_ce0 <= grp_compute_blur_fu_56_out_c_ce0;
        else 
            temp2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    temp2_we0_assign_proc : process(grp_compute_blur_fu_56_out_c_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            temp2_we0 <= grp_compute_blur_fu_56_out_c_we0;
        else 
            temp2_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
