-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matrix_mult_bram is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    A_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_EN_A : OUT STD_LOGIC;
    A_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    A_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    A_Clk_A : OUT STD_LOGIC;
    A_Rst_A : OUT STD_LOGIC;
    A_Addr_B : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_EN_B : OUT STD_LOGIC;
    A_WEN_B : OUT STD_LOGIC_VECTOR (3 downto 0);
    A_Din_B : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_Dout_B : IN STD_LOGIC_VECTOR (31 downto 0);
    A_Clk_B : OUT STD_LOGIC;
    A_Rst_B : OUT STD_LOGIC;
    B_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_EN_A : OUT STD_LOGIC;
    B_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    B_Clk_A : OUT STD_LOGIC;
    B_Rst_A : OUT STD_LOGIC;
    B_Addr_B : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_EN_B : OUT STD_LOGIC;
    B_WEN_B : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_Din_B : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_Dout_B : IN STD_LOGIC_VECTOR (31 downto 0);
    B_Clk_B : OUT STD_LOGIC;
    B_Rst_B : OUT STD_LOGIC;
    C_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    C_EN_A : OUT STD_LOGIC;
    C_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    C_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    C_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    C_Clk_A : OUT STD_LOGIC;
    C_Rst_A : OUT STD_LOGIC );
end;


architecture behav of matrix_mult_bram is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matrix_mult_bram_matrix_mult_bram,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu13p-fsga2577-2-e,HLS_INPUT_CLOCK=25.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.030000,HLS_SYN_LAT=110,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=163,HLS_SYN_LUT=659,HLS_VERSION=2024_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv6_2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_const_lv6_3 : STD_LOGIC_VECTOR (5 downto 0) := "000011";
    constant ap_const_lv5_C : STD_LOGIC_VECTOR (4 downto 0) := "01100";
    constant ap_const_lv5_12 : STD_LOGIC_VECTOR (4 downto 0) := "10010";
    constant ap_const_lv6_4 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_const_lv6_5 : STD_LOGIC_VECTOR (5 downto 0) := "000101";
    constant ap_const_lv6_1E : STD_LOGIC_VECTOR (5 downto 0) := "011110";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv6_23 : STD_LOGIC_VECTOR (5 downto 0) := "100011";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal icmp_ln37_fu_492_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage2 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal select_ln37_fu_272_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln37_reg_555 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal empty_fu_308_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_reg_563 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal grp_fu_229_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln42_reg_612 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_235_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln42_2_reg_617 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal add_ln45_fu_465_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln45_reg_642 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln42_4_reg_647 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln42_fu_470_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln42_reg_652 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln38_fu_486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_657 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln37_reg_662 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_phi_mux_icmp_ln384_phi_fu_222_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal p_cast_fu_314_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_1_cast_fu_337_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln38_fu_342_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln42_3_fu_357_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast7_fu_372_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal p_cast8_fu_382_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln42_4_fu_396_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln42_5_fu_407_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast9_fu_420_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal p_cast10_fu_430_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln42_6_fu_449_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln42_7_fu_460_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln45_fu_508_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal indvar_flatten1_fu_80 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln37_1_fu_480_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal i2_fu_84 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal i_fu_280_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_i2_load : STD_LOGIC_VECTOR (2 downto 0);
    signal j3_fu_88 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal j_fu_475_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_j3_load : STD_LOGIC_VECTOR (2 downto 0);
    signal A_EN_B_local : STD_LOGIC;
    signal A_Addr_B_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal A_EN_A_local : STD_LOGIC;
    signal A_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal B_EN_B_local : STD_LOGIC;
    signal B_Addr_B_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal B_EN_A_local : STD_LOGIC;
    signal B_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal C_WEN_A_local : STD_LOGIC_VECTOR (3 downto 0);
    signal sum_fu_527_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal C_EN_A_local : STD_LOGIC;
    signal C_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_229_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_229_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_235_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_235_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln37_fu_266_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_296_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl_fu_288_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl30_fu_304_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_cast_fu_319_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_1_fu_329_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln42_2_fu_347_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln42_4_fu_351_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_6_fu_367_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_7_fu_377_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln42_1_fu_387_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln42_5_fu_390_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln42_6_fu_401_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal empty_8_fu_415_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_9_fu_425_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_438_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln42_fu_445_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln42_fu_435_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln42_7_fu_454_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln42_2_fu_516_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln42_3_fu_522_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln42_1_fu_512_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_499 : BOOLEAN;
    signal ap_condition_207 : BOOLEAN;
    signal ap_condition_504 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component matrix_mult_bram_mul_32s_32s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component matrix_mult_bram_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    mul_32s_32s_32_1_1_U1 : component matrix_mult_bram_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => grp_fu_229_p0,
        din1 => grp_fu_229_p1,
        dout => grp_fu_229_p2);

    mul_32s_32s_32_1_1_U2 : component matrix_mult_bram_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => grp_fu_235_p0,
        din1 => grp_fu_235_p1,
        dout => grp_fu_235_p2);

    flow_control_loop_pipe_U : component matrix_mult_bram_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage2,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_const_logic_1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_loop_exit_ready = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_idle_pp0_0to0 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    i2_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_207)) then
                i2_fu_84 <= i_fu_280_p3;
            end if;
        end if;
    end process;

    indvar_flatten1_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
                if ((ap_const_boolean_1 = ap_condition_504)) then 
                    indvar_flatten1_fu_80 <= ap_const_lv6_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    indvar_flatten1_fu_80 <= add_ln37_1_fu_480_p2;
                end if;
            end if; 
        end if;
    end process;

    j3_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
                if ((ap_const_boolean_1 = ap_condition_504)) then 
                    j3_fu_88 <= ap_const_lv3_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    j3_fu_88 <= j_fu_475_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                add_ln42_reg_652 <= add_ln42_fu_470_p2;
                add_ln45_reg_642 <= add_ln45_fu_465_p2;
                icmp_ln37_reg_662 <= icmp_ln37_fu_492_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    empty_reg_563(5 downto 1) <= empty_fu_308_p2(5 downto 1);
                select_ln37_reg_555 <= select_ln37_fu_272_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                icmp_ln38_reg_657 <= icmp_ln38_fu_486_p2;
                mul_ln42_4_reg_647 <= grp_fu_235_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                mul_ln42_2_reg_617 <= grp_fu_235_p2;
                mul_ln42_reg_612 <= grp_fu_229_p2;
            end if;
        end if;
    end process;
    empty_reg_563(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage2_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter1_stage0, ap_idle_pp0_0to0, ap_idle_pp0_1to1, ap_block_pp0_stage1_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_idle_pp0_0to0 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    A_Addr_A <= std_logic_vector(shift_left(unsigned(A_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));

    A_Addr_A_orig_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, tmp_1_cast_fu_337_p1, ap_block_pp0_stage1, p_cast8_fu_382_p1, ap_block_pp0_stage2, p_cast10_fu_430_p1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                A_Addr_A_orig <= p_cast10_fu_430_p1(32 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                A_Addr_A_orig <= p_cast8_fu_382_p1(32 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                A_Addr_A_orig <= tmp_1_cast_fu_337_p1(32 - 1 downto 0);
            else 
                A_Addr_A_orig <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            A_Addr_A_orig <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    A_Addr_B <= std_logic_vector(shift_left(unsigned(A_Addr_B_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));

    A_Addr_B_orig_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, p_cast_fu_314_p1, p_cast7_fu_372_p1, ap_block_pp0_stage1, p_cast9_fu_420_p1, ap_block_pp0_stage2)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                A_Addr_B_orig <= p_cast9_fu_420_p1(32 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                A_Addr_B_orig <= p_cast7_fu_372_p1(32 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                A_Addr_B_orig <= p_cast_fu_314_p1(32 - 1 downto 0);
            else 
                A_Addr_B_orig <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            A_Addr_B_orig <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    A_Clk_A <= ap_clk;
    A_Clk_B <= ap_clk;
    A_Din_A <= ap_const_lv32_0;
    A_Din_B <= ap_const_lv32_0;
    A_EN_A <= A_EN_A_local;

    A_EN_A_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            A_EN_A_local <= ap_const_logic_1;
        else 
            A_EN_A_local <= ap_const_logic_0;
        end if; 
    end process;

    A_EN_B <= A_EN_B_local;

    A_EN_B_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            A_EN_B_local <= ap_const_logic_1;
        else 
            A_EN_B_local <= ap_const_logic_0;
        end if; 
    end process;

    A_Rst_A <= ap_rst;
    A_Rst_B <= ap_rst;
    A_WEN_A <= ap_const_lv4_0;
    A_WEN_B <= ap_const_lv4_0;
    B_Addr_A <= std_logic_vector(shift_left(unsigned(B_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));

    B_Addr_A_orig_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln42_3_fu_357_p1, ap_block_pp0_stage1, zext_ln42_5_fu_407_p1, ap_block_pp0_stage2, zext_ln42_7_fu_460_p1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                B_Addr_A_orig <= zext_ln42_7_fu_460_p1(32 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                B_Addr_A_orig <= zext_ln42_5_fu_407_p1(32 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                B_Addr_A_orig <= zext_ln42_3_fu_357_p1(32 - 1 downto 0);
            else 
                B_Addr_A_orig <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            B_Addr_A_orig <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    B_Addr_B <= std_logic_vector(shift_left(unsigned(B_Addr_B_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));

    B_Addr_B_orig_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln38_fu_342_p1, ap_block_pp0_stage1, zext_ln42_4_fu_396_p1, ap_block_pp0_stage2, zext_ln42_6_fu_449_p1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                B_Addr_B_orig <= zext_ln42_6_fu_449_p1(32 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                B_Addr_B_orig <= zext_ln42_4_fu_396_p1(32 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                B_Addr_B_orig <= zext_ln38_fu_342_p1(32 - 1 downto 0);
            else 
                B_Addr_B_orig <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            B_Addr_B_orig <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    B_Clk_A <= ap_clk;
    B_Clk_B <= ap_clk;
    B_Din_A <= ap_const_lv32_0;
    B_Din_B <= ap_const_lv32_0;
    B_EN_A <= B_EN_A_local;

    B_EN_A_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            B_EN_A_local <= ap_const_logic_1;
        else 
            B_EN_A_local <= ap_const_logic_0;
        end if; 
    end process;

    B_EN_B <= B_EN_B_local;

    B_EN_B_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            B_EN_B_local <= ap_const_logic_1;
        else 
            B_EN_B_local <= ap_const_logic_0;
        end if; 
    end process;

    B_Rst_A <= ap_rst;
    B_Rst_B <= ap_rst;
    B_WEN_A <= ap_const_lv4_0;
    B_WEN_B <= ap_const_lv4_0;
    C_Addr_A <= std_logic_vector(shift_left(unsigned(C_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    C_Addr_A_orig <= zext_ln45_fu_508_p1(32 - 1 downto 0);
    C_Clk_A <= ap_clk;
    C_Din_A <= sum_fu_527_p2;
    C_EN_A <= C_EN_A_local;

    C_EN_A_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_EN_A_local <= ap_const_logic_1;
        else 
            C_EN_A_local <= ap_const_logic_0;
        end if; 
    end process;

    C_Rst_A <= ap_rst;
    C_WEN_A <= C_WEN_A_local;

    C_WEN_A_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_WEN_A_local <= ap_const_lv4_F;
        else 
            C_WEN_A_local <= ap_const_lv4_0;
        end if; 
    end process;

    add_ln37_1_fu_480_p2 <= std_logic_vector(unsigned(indvar_flatten1_fu_80) + unsigned(ap_const_lv6_1));
    add_ln37_fu_266_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i2_load) + unsigned(ap_const_lv3_1));
    add_ln42_1_fu_512_p2 <= std_logic_vector(unsigned(add_ln42_reg_652) + unsigned(mul_ln42_2_reg_617));
    add_ln42_2_fu_516_p2 <= std_logic_vector(unsigned(grp_fu_235_p2) + unsigned(grp_fu_229_p2));
    add_ln42_3_fu_522_p2 <= std_logic_vector(unsigned(add_ln42_2_fu_516_p2) + unsigned(mul_ln42_4_reg_647));
    add_ln42_4_fu_351_p2 <= std_logic_vector(unsigned(zext_ln42_2_fu_347_p1) + unsigned(ap_const_lv4_6));
    add_ln42_5_fu_390_p2 <= std_logic_vector(unsigned(zext_ln42_1_fu_387_p1) + unsigned(ap_const_lv5_C));
    add_ln42_6_fu_401_p2 <= std_logic_vector(unsigned(zext_ln42_1_fu_387_p1) + unsigned(ap_const_lv5_12));
    add_ln42_7_fu_454_p2 <= std_logic_vector(unsigned(zext_ln42_fu_435_p1) + unsigned(ap_const_lv6_1E));
    add_ln42_fu_470_p2 <= std_logic_vector(unsigned(mul_ln42_reg_612) + unsigned(grp_fu_229_p2));
    add_ln45_fu_465_p2 <= std_logic_vector(unsigned(empty_reg_563) + unsigned(zext_ln42_fu_435_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_207_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_207 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_499_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln37_reg_662, ap_block_pp0_stage0)
    begin
                ap_condition_499 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln37_reg_662 = ap_const_lv1_0));
    end process;


    ap_condition_504_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_loop_init)
    begin
                ap_condition_504 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage2_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, icmp_ln37_fu_492_p2)
    begin
        if (((icmp_ln37_fu_492_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln37_reg_662, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln37_reg_662 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage2;

    ap_phi_mux_icmp_ln384_phi_fu_222_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln38_reg_657, ap_loop_init, ap_condition_499)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
            if ((ap_const_boolean_1 = ap_condition_499)) then 
                ap_phi_mux_icmp_ln384_phi_fu_222_p4 <= icmp_ln38_reg_657;
            elsif ((ap_loop_init = ap_const_logic_1)) then 
                ap_phi_mux_icmp_ln384_phi_fu_222_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_icmp_ln384_phi_fu_222_p4 <= icmp_ln38_reg_657;
            end if;
        else 
            ap_phi_mux_icmp_ln384_phi_fu_222_p4 <= icmp_ln38_reg_657;
        end if; 
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i2_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_loop_init, ap_block_pp0_stage0, i2_fu_84)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i2_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_i2_load <= i2_fu_84;
        end if; 
    end process;


    ap_sig_allocacmp_j3_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_loop_init, ap_block_pp0_stage0, j3_fu_88)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j3_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_j3_load <= j3_fu_88;
        end if; 
    end process;

    empty_6_fu_367_p2 <= std_logic_vector(unsigned(empty_reg_563) + unsigned(ap_const_lv6_2));
    empty_7_fu_377_p2 <= std_logic_vector(unsigned(empty_reg_563) + unsigned(ap_const_lv6_3));
    empty_8_fu_415_p2 <= std_logic_vector(unsigned(empty_reg_563) + unsigned(ap_const_lv6_4));
    empty_9_fu_425_p2 <= std_logic_vector(unsigned(empty_reg_563) + unsigned(ap_const_lv6_5));
    empty_fu_308_p2 <= std_logic_vector(unsigned(p_shl_fu_288_p3) - unsigned(p_shl30_fu_304_p1));

    grp_fu_229_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, B_Dout_A, B_Dout_B, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_229_p0 <= B_Dout_A;
        elsif ((((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            grp_fu_229_p0 <= B_Dout_B;
        else 
            grp_fu_229_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_229_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, A_Dout_A, A_Dout_B, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_229_p1 <= A_Dout_A;
        elsif ((((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            grp_fu_229_p1 <= A_Dout_B;
        else 
            grp_fu_229_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_235_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, B_Dout_A, B_Dout_B, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_235_p0 <= B_Dout_B;
        elsif ((((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            grp_fu_235_p0 <= B_Dout_A;
        else 
            grp_fu_235_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_235_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, A_Dout_A, A_Dout_B, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_235_p1 <= A_Dout_B;
        elsif ((((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            grp_fu_235_p1 <= A_Dout_A;
        else 
            grp_fu_235_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    i_fu_280_p3 <= 
        add_ln37_fu_266_p2 when (ap_phi_mux_icmp_ln384_phi_fu_222_p4(0) = '1') else 
        ap_sig_allocacmp_i2_load;
    icmp_ln37_fu_492_p2 <= "1" when (indvar_flatten1_fu_80 = ap_const_lv6_23) else "0";
    icmp_ln38_fu_486_p2 <= "1" when (j_fu_475_p2 = ap_const_lv3_6) else "0";
    j_fu_475_p2 <= std_logic_vector(unsigned(select_ln37_reg_555) + unsigned(ap_const_lv3_1));
    p_cast10_fu_430_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_9_fu_425_p2),64));
    p_cast7_fu_372_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_6_fu_367_p2),64));
    p_cast8_fu_382_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_7_fu_377_p2),64));
    p_cast9_fu_420_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_8_fu_415_p2),64));
    p_cast_fu_314_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_fu_308_p2),64));
    p_shl30_fu_304_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_296_p3),6));
    p_shl_fu_288_p3 <= (i_fu_280_p3 & ap_const_lv3_0);
    select_ln37_fu_272_p3 <= 
        ap_const_lv3_0 when (ap_phi_mux_icmp_ln384_phi_fu_222_p4(0) = '1') else 
        ap_sig_allocacmp_j3_load;
        sext_ln42_fu_445_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2_fu_438_p3),5));

    sum_fu_527_p2 <= std_logic_vector(unsigned(add_ln42_3_fu_522_p2) + unsigned(add_ln42_1_fu_512_p2));
    tmp_1_cast_fu_337_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_329_p3),64));
    tmp_1_fu_329_p3 <= (tmp_cast_fu_319_p4 & ap_const_lv1_1);
    tmp_2_fu_438_p3 <= (ap_const_lv1_1 & select_ln37_reg_555);
    tmp_cast_fu_319_p4 <= empty_fu_308_p2(5 downto 1);
    tmp_fu_296_p3 <= (i_fu_280_p3 & ap_const_lv1_0);
    zext_ln38_fu_342_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln37_fu_272_p3),64));
    zext_ln42_1_fu_387_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln37_reg_555),5));
    zext_ln42_2_fu_347_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln37_fu_272_p3),4));
    zext_ln42_3_fu_357_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln42_4_fu_351_p2),64));
    zext_ln42_4_fu_396_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln42_5_fu_390_p2),64));
    zext_ln42_5_fu_407_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln42_6_fu_401_p2),64));
    zext_ln42_6_fu_449_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln42_fu_445_p1),64));
    zext_ln42_7_fu_460_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln42_7_fu_454_p2),64));
    zext_ln42_fu_435_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln37_reg_555),6));
    zext_ln45_fu_508_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln45_reg_642),64));
end behav;
