// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="hw5_ex1_hw5_ex1,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu13p-fsga2577-2-e,HLS_INPUT_CLOCK=25.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.913812,HLS_SYN_LAT=108,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=449,HLS_SYN_LUT=1230,HLS_VERSION=2024_1}" *)

module hw5_ex1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_address0,
        A_ce0,
        A_q0,
        B_address0,
        B_ce0,
        B_we0,
        B_d0
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] A_address0;
output   A_ce0;
input  [31:0] A_q0;
output  [4:0] B_address0;
output   B_ce0;
output   B_we0;
output  [31:0] B_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [3:0] temp1_address0;
reg    temp1_ce0;
reg    temp1_we0;
wire   [31:0] temp1_q0;
reg   [3:0] temp1_1_address0;
reg    temp1_1_ce0;
reg    temp1_1_we0;
wire   [31:0] temp1_1_q0;
reg   [3:0] temp1_2_address0;
reg    temp1_2_ce0;
reg    temp1_2_we0;
wire   [31:0] temp1_2_q0;
reg   [4:0] temp2_address0;
reg    temp2_ce0;
reg    temp2_we0;
reg   [30:0] temp2_d0;
wire   [30:0] temp2_q0;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_ap_start;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_ap_done;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_ap_idle;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_ap_ready;
wire   [4:0] grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_temp2_address0;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_temp2_ce0;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_temp2_we0;
wire   [30:0] grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_temp2_d0;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_ap_start;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_ap_done;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_ap_idle;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_ap_ready;
wire   [3:0] grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_2_address0;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_2_ce0;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_2_we0;
wire   [31:0] grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_2_d0;
wire   [3:0] grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_1_address0;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_1_ce0;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_1_we0;
wire   [31:0] grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_1_d0;
wire   [3:0] grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_address0;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_ce0;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_we0;
wire   [31:0] grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_d0;
wire   [4:0] grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_A_address0;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_A_ce0;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_ap_start;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_ap_done;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_ap_idle;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_ap_ready;
wire   [3:0] grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp1_address0;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp1_ce0;
wire   [3:0] grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp1_1_address0;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp1_1_ce0;
wire   [3:0] grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp1_2_address0;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp1_2_ce0;
wire   [4:0] grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp2_address0;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp2_ce0;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp2_we0;
wire   [30:0] grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp2_d0;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_ap_start;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_ap_done;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_ap_idle;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_ap_ready;
wire   [4:0] grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_temp2_address0;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_temp2_ce0;
wire   [4:0] grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_B_address0;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_B_ce0;
wire    grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_B_we0;
wire   [31:0] grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_B_d0;
reg    grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_ap_start_reg;
reg    grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_block_state2_on_subcall_done;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_ap_start_reg = 1'b0;
#0 grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_ap_start_reg = 1'b0;
#0 grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_ap_start_reg = 1'b0;
#0 grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_ap_start_reg = 1'b0;
end

hw5_ex1_temp1_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
temp1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp1_address0),
    .ce0(temp1_ce0),
    .we0(temp1_we0),
    .d0(grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_d0),
    .q0(temp1_q0)
);

hw5_ex1_temp1_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
temp1_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp1_1_address0),
    .ce0(temp1_1_ce0),
    .we0(temp1_1_we0),
    .d0(grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_1_d0),
    .q0(temp1_1_q0)
);

hw5_ex1_temp1_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
temp1_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp1_2_address0),
    .ce0(temp1_2_ce0),
    .we0(temp1_2_we0),
    .d0(grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_2_d0),
    .q0(temp1_2_q0)
);

hw5_ex1_temp2_RAM_AUTO_1R1W #(
    .DataWidth( 31 ),
    .AddressRange( 30 ),
    .AddressWidth( 5 ))
temp2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp2_address0),
    .ce0(temp2_ce0),
    .we0(temp2_we0),
    .d0(temp2_d0),
    .q0(temp2_q0)
);

hw5_ex1_hw5_ex1_Pipeline_VITIS_LOOP_25_1 grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_ap_start),
    .ap_done(grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_ap_done),
    .ap_idle(grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_ap_idle),
    .ap_ready(grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_ap_ready),
    .temp2_address0(grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_temp2_address0),
    .temp2_ce0(grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_temp2_ce0),
    .temp2_we0(grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_temp2_we0),
    .temp2_d0(grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_temp2_d0)
);

hw5_ex1_hw5_ex1_Pipeline_VITIS_LOOP_5_1 grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_ap_start),
    .ap_done(grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_ap_done),
    .ap_idle(grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_ap_idle),
    .ap_ready(grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_ap_ready),
    .temp1_2_address0(grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_2_address0),
    .temp1_2_ce0(grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_2_ce0),
    .temp1_2_we0(grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_2_we0),
    .temp1_2_d0(grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_2_d0),
    .temp1_1_address0(grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_1_address0),
    .temp1_1_ce0(grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_1_ce0),
    .temp1_1_we0(grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_1_we0),
    .temp1_1_d0(grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_1_d0),
    .temp1_address0(grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_address0),
    .temp1_ce0(grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_ce0),
    .temp1_we0(grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_we0),
    .temp1_d0(grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_d0),
    .A_address0(grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_A_address0),
    .A_ce0(grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_A_ce0),
    .A_q0(A_q0)
);

hw5_ex1_hw5_ex1_Pipeline_VITIS_LOOP_11_1 grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_ap_start),
    .ap_done(grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_ap_done),
    .ap_idle(grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_ap_idle),
    .ap_ready(grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_ap_ready),
    .temp1_address0(grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp1_address0),
    .temp1_ce0(grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp1_ce0),
    .temp1_q0(temp1_q0),
    .temp1_1_address0(grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp1_1_address0),
    .temp1_1_ce0(grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp1_1_ce0),
    .temp1_1_q0(temp1_1_q0),
    .temp1_2_address0(grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp1_2_address0),
    .temp1_2_ce0(grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp1_2_ce0),
    .temp1_2_q0(temp1_2_q0),
    .temp2_address0(grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp2_address0),
    .temp2_ce0(grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp2_ce0),
    .temp2_we0(grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp2_we0),
    .temp2_d0(grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp2_d0)
);

hw5_ex1_hw5_ex1_Pipeline_VITIS_LOOP_17_1 grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_ap_start),
    .ap_done(grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_ap_done),
    .ap_idle(grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_ap_idle),
    .ap_ready(grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_ap_ready),
    .temp2_address0(grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_temp2_address0),
    .temp2_ce0(grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_temp2_ce0),
    .temp2_q0(temp2_q0),
    .B_address0(grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_B_address0),
    .B_ce0(grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_B_ce0),
    .B_we0(grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_B_we0),
    .B_d0(grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_B_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_ap_start_reg <= 1'b1;
        end else if ((grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_ap_ready == 1'b1)) begin
            grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_ap_start_reg <= 1'b1;
        end else if ((grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_ap_ready == 1'b1)) begin
            grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_ap_start_reg <= 1'b1;
        end else if ((grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_ap_ready == 1'b1)) begin
            grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_ap_start_reg <= 1'b1;
        end else if ((grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_ap_ready == 1'b1)) begin
            grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        temp1_1_address0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp1_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        temp1_1_address0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_1_address0;
    end else begin
        temp1_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        temp1_1_ce0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp1_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        temp1_1_ce0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_1_ce0;
    end else begin
        temp1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        temp1_1_we0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_1_we0;
    end else begin
        temp1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        temp1_2_address0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp1_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        temp1_2_address0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_2_address0;
    end else begin
        temp1_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        temp1_2_ce0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp1_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        temp1_2_ce0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_2_ce0;
    end else begin
        temp1_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        temp1_2_we0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_2_we0;
    end else begin
        temp1_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        temp1_address0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        temp1_address0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_address0;
    end else begin
        temp1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        temp1_ce0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        temp1_ce0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_ce0;
    end else begin
        temp1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        temp1_we0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_temp1_we0;
    end else begin
        temp1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        temp2_address0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_temp2_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        temp2_address0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        temp2_address0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_temp2_address0;
    end else begin
        temp2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        temp2_ce0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_temp2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        temp2_ce0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        temp2_ce0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_temp2_ce0;
    end else begin
        temp2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        temp2_d0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp2_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        temp2_d0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_temp2_d0;
    end else begin
        temp2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        temp2_we0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_temp2_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        temp2_we0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_temp2_we0;
    end else begin
        temp2_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_address0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_A_address0;

assign A_ce0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_A_ce0;

assign B_address0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_B_address0;

assign B_ce0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_B_ce0;

assign B_d0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_B_d0;

assign B_we0 = grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_B_we0;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_ap_done == 1'b0) | (grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_ap_done == 1'b0));
end

assign grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_ap_start = grp_hw5_ex1_Pipeline_VITIS_LOOP_11_1_fu_64_ap_start_reg;

assign grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_ap_start = grp_hw5_ex1_Pipeline_VITIS_LOOP_17_1_fu_72_ap_start_reg;

assign grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_ap_start = grp_hw5_ex1_Pipeline_VITIS_LOOP_25_1_fu_46_ap_start_reg;

assign grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_ap_start = grp_hw5_ex1_Pipeline_VITIS_LOOP_5_1_fu_52_ap_start_reg;

endmodule //hw5_ex1
