-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity q5_cyclic_partition is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 4;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    A_0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    A_0_ce0 : OUT STD_LOGIC;
    A_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    A_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    A_1_ce0 : OUT STD_LOGIC;
    A_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    A_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    A_2_ce0 : OUT STD_LOGIC;
    A_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    A_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    A_3_ce0 : OUT STD_LOGIC;
    A_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    B_0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_0_ce0 : OUT STD_LOGIC;
    B_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    B_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_1_ce0 : OUT STD_LOGIC;
    B_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    B_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_2_ce0 : OUT STD_LOGIC;
    B_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    B_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_3_ce0 : OUT STD_LOGIC;
    B_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    C_0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    C_0_ce0 : OUT STD_LOGIC;
    C_0_we0 : OUT STD_LOGIC;
    C_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    C_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    C_1_ce0 : OUT STD_LOGIC;
    C_1_we0 : OUT STD_LOGIC;
    C_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    C_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    C_2_ce0 : OUT STD_LOGIC;
    C_2_we0 : OUT STD_LOGIC;
    C_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    C_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    C_3_ce0 : OUT STD_LOGIC;
    C_3_we0 : OUT STD_LOGIC;
    C_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    D_0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    D_0_ce0 : OUT STD_LOGIC;
    D_0_we0 : OUT STD_LOGIC;
    D_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    D_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    D_1_ce0 : OUT STD_LOGIC;
    D_1_we0 : OUT STD_LOGIC;
    D_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    D_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    D_2_ce0 : OUT STD_LOGIC;
    D_2_we0 : OUT STD_LOGIC;
    D_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    D_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    D_3_ce0 : OUT STD_LOGIC;
    D_3_we0 : OUT STD_LOGIC;
    D_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    E_0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    E_0_ce0 : OUT STD_LOGIC;
    E_0_we0 : OUT STD_LOGIC;
    E_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    E_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    E_1_ce0 : OUT STD_LOGIC;
    E_1_we0 : OUT STD_LOGIC;
    E_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    E_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    E_2_ce0 : OUT STD_LOGIC;
    E_2_we0 : OUT STD_LOGIC;
    E_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    E_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    E_3_ce0 : OUT STD_LOGIC;
    E_3_we0 : OUT STD_LOGIC;
    E_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of q5_cyclic_partition is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "q5_cyclic_partition_q5_cyclic_partition,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu13p-fsga2577-2-e,HLS_INPUT_CLOCK=25.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.448000,HLS_SYN_LAT=18,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=51,HLS_SYN_LUT=566,HLS_VERSION=2024_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv7_4 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal tmp_fu_436_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal zext_ln117_fu_418_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln117_reg_516 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal i1_fu_88 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal i_fu_430_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i1_load : STD_LOGIC_VECTOR (6 downto 0);
    signal A_0_ce0_local : STD_LOGIC;
    signal B_0_ce0_local : STD_LOGIC;
    signal A_1_ce0_local : STD_LOGIC;
    signal A_2_ce0_local : STD_LOGIC;
    signal A_3_ce0_local : STD_LOGIC;
    signal B_1_ce0_local : STD_LOGIC;
    signal B_2_ce0_local : STD_LOGIC;
    signal B_3_ce0_local : STD_LOGIC;
    signal C_0_we0_local : STD_LOGIC;
    signal sum_fu_449_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal C_0_ce0_local : STD_LOGIC;
    signal C_1_we0_local : STD_LOGIC;
    signal sum_4_fu_464_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal C_1_ce0_local : STD_LOGIC;
    signal C_2_we0_local : STD_LOGIC;
    signal sum_5_fu_479_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal C_2_ce0_local : STD_LOGIC;
    signal C_3_we0_local : STD_LOGIC;
    signal sum_3_fu_494_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal C_3_ce0_local : STD_LOGIC;
    signal D_0_we0_local : STD_LOGIC;
    signal mul_ln124_fu_352_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal D_0_ce0_local : STD_LOGIC;
    signal D_1_we0_local : STD_LOGIC;
    signal mul_ln124_1_fu_364_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal D_1_ce0_local : STD_LOGIC;
    signal D_2_we0_local : STD_LOGIC;
    signal mul_ln124_2_fu_376_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal D_2_ce0_local : STD_LOGIC;
    signal D_3_we0_local : STD_LOGIC;
    signal mul_ln124_3_fu_388_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal D_3_ce0_local : STD_LOGIC;
    signal E_0_we0_local : STD_LOGIC;
    signal mul_ln125_fu_359_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal E_0_ce0_local : STD_LOGIC;
    signal E_1_we0_local : STD_LOGIC;
    signal mul_ln125_1_fu_371_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal E_1_ce0_local : STD_LOGIC;
    signal E_2_we0_local : STD_LOGIC;
    signal mul_ln125_2_fu_383_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal E_2_ce0_local : STD_LOGIC;
    signal E_3_we0_local : STD_LOGIC;
    signal mul_ln125_3_fu_395_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal E_3_ce0_local : STD_LOGIC;
    signal mul_ln125_fu_359_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln125_1_fu_371_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln125_2_fu_383_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln125_3_fu_395_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln_fu_408_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal sum_fu_449_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_fu_449_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal diff_fu_457_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal diff_fu_457_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_4_fu_464_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_4_fu_464_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal diff_4_fu_472_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal diff_4_fu_472_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_5_fu_479_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_5_fu_479_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal diff_5_fu_487_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal diff_5_fu_487_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_3_fu_494_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_3_fu_494_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal diff_3_fu_502_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal diff_3_fu_502_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_263 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component q5_cyclic_partition_mul_32s_32s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component q5_cyclic_partition_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component q5_cyclic_partition_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    control_s_axi_U : component q5_cyclic_partition_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    mul_32s_32s_32_1_1_U1 : component q5_cyclic_partition_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => B_0_q0,
        din1 => A_0_q0,
        dout => mul_ln124_fu_352_p2);

    mul_32s_32s_32_1_1_U2 : component q5_cyclic_partition_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => sum_fu_449_p2,
        din1 => mul_ln125_fu_359_p1,
        dout => mul_ln125_fu_359_p2);

    mul_32s_32s_32_1_1_U3 : component q5_cyclic_partition_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => B_1_q0,
        din1 => A_1_q0,
        dout => mul_ln124_1_fu_364_p2);

    mul_32s_32s_32_1_1_U4 : component q5_cyclic_partition_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => sum_4_fu_464_p2,
        din1 => mul_ln125_1_fu_371_p1,
        dout => mul_ln125_1_fu_371_p2);

    mul_32s_32s_32_1_1_U5 : component q5_cyclic_partition_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => B_2_q0,
        din1 => A_2_q0,
        dout => mul_ln124_2_fu_376_p2);

    mul_32s_32s_32_1_1_U6 : component q5_cyclic_partition_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => sum_5_fu_479_p2,
        din1 => mul_ln125_2_fu_383_p1,
        dout => mul_ln125_2_fu_383_p2);

    mul_32s_32s_32_1_1_U7 : component q5_cyclic_partition_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => B_3_q0,
        din1 => A_3_q0,
        dout => mul_ln124_3_fu_388_p2);

    mul_32s_32s_32_1_1_U8 : component q5_cyclic_partition_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => sum_3_fu_494_p2,
        din1 => mul_ln125_3_fu_395_p1,
        dout => mul_ln125_3_fu_395_p2);

    flow_control_loop_pipe_U : component q5_cyclic_partition_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_const_logic_1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if (((ap_loop_exit_ready = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
                    ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                end if;
            end if; 
        end if;
    end process;

    i1_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_263)) then
                i1_fu_88 <= i_fu_430_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    zext_ln117_reg_516(3 downto 0) <= zext_ln117_fu_418_p1(3 downto 0);
            end if;
        end if;
    end process;
    zext_ln117_reg_516(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    A_0_address0 <= zext_ln117_fu_418_p1(4 - 1 downto 0);
    A_0_ce0 <= A_0_ce0_local;

    A_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            A_0_ce0_local <= ap_const_logic_1;
        else 
            A_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_1_address0 <= zext_ln117_fu_418_p1(4 - 1 downto 0);
    A_1_ce0 <= A_1_ce0_local;

    A_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            A_1_ce0_local <= ap_const_logic_1;
        else 
            A_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_2_address0 <= zext_ln117_fu_418_p1(4 - 1 downto 0);
    A_2_ce0 <= A_2_ce0_local;

    A_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            A_2_ce0_local <= ap_const_logic_1;
        else 
            A_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_3_address0 <= zext_ln117_fu_418_p1(4 - 1 downto 0);
    A_3_ce0 <= A_3_ce0_local;

    A_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            A_3_ce0_local <= ap_const_logic_1;
        else 
            A_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_0_address0 <= zext_ln117_fu_418_p1(4 - 1 downto 0);
    B_0_ce0 <= B_0_ce0_local;

    B_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            B_0_ce0_local <= ap_const_logic_1;
        else 
            B_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_1_address0 <= zext_ln117_fu_418_p1(4 - 1 downto 0);
    B_1_ce0 <= B_1_ce0_local;

    B_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            B_1_ce0_local <= ap_const_logic_1;
        else 
            B_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_2_address0 <= zext_ln117_fu_418_p1(4 - 1 downto 0);
    B_2_ce0 <= B_2_ce0_local;

    B_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            B_2_ce0_local <= ap_const_logic_1;
        else 
            B_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_3_address0 <= zext_ln117_fu_418_p1(4 - 1 downto 0);
    B_3_ce0 <= B_3_ce0_local;

    B_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            B_3_ce0_local <= ap_const_logic_1;
        else 
            B_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_0_address0 <= zext_ln117_reg_516(4 - 1 downto 0);
    C_0_ce0 <= C_0_ce0_local;

    C_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_0_ce0_local <= ap_const_logic_1;
        else 
            C_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_0_d0 <= sum_fu_449_p2;
    C_0_we0 <= C_0_we0_local;

    C_0_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_0_we0_local <= ap_const_logic_1;
        else 
            C_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_1_address0 <= zext_ln117_reg_516(4 - 1 downto 0);
    C_1_ce0 <= C_1_ce0_local;

    C_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_1_ce0_local <= ap_const_logic_1;
        else 
            C_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_1_d0 <= sum_4_fu_464_p2;
    C_1_we0 <= C_1_we0_local;

    C_1_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_1_we0_local <= ap_const_logic_1;
        else 
            C_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_2_address0 <= zext_ln117_reg_516(4 - 1 downto 0);
    C_2_ce0 <= C_2_ce0_local;

    C_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_2_ce0_local <= ap_const_logic_1;
        else 
            C_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_2_d0 <= sum_5_fu_479_p2;
    C_2_we0 <= C_2_we0_local;

    C_2_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_2_we0_local <= ap_const_logic_1;
        else 
            C_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_3_address0 <= zext_ln117_reg_516(4 - 1 downto 0);
    C_3_ce0 <= C_3_ce0_local;

    C_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_3_ce0_local <= ap_const_logic_1;
        else 
            C_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_3_d0 <= sum_3_fu_494_p2;
    C_3_we0 <= C_3_we0_local;

    C_3_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_3_we0_local <= ap_const_logic_1;
        else 
            C_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    D_0_address0 <= zext_ln117_reg_516(4 - 1 downto 0);
    D_0_ce0 <= D_0_ce0_local;

    D_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            D_0_ce0_local <= ap_const_logic_1;
        else 
            D_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    D_0_d0 <= mul_ln124_fu_352_p2;
    D_0_we0 <= D_0_we0_local;

    D_0_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            D_0_we0_local <= ap_const_logic_1;
        else 
            D_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    D_1_address0 <= zext_ln117_reg_516(4 - 1 downto 0);
    D_1_ce0 <= D_1_ce0_local;

    D_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            D_1_ce0_local <= ap_const_logic_1;
        else 
            D_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    D_1_d0 <= mul_ln124_1_fu_364_p2;
    D_1_we0 <= D_1_we0_local;

    D_1_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            D_1_we0_local <= ap_const_logic_1;
        else 
            D_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    D_2_address0 <= zext_ln117_reg_516(4 - 1 downto 0);
    D_2_ce0 <= D_2_ce0_local;

    D_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            D_2_ce0_local <= ap_const_logic_1;
        else 
            D_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    D_2_d0 <= mul_ln124_2_fu_376_p2;
    D_2_we0 <= D_2_we0_local;

    D_2_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            D_2_we0_local <= ap_const_logic_1;
        else 
            D_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    D_3_address0 <= zext_ln117_reg_516(4 - 1 downto 0);
    D_3_ce0 <= D_3_ce0_local;

    D_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            D_3_ce0_local <= ap_const_logic_1;
        else 
            D_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    D_3_d0 <= mul_ln124_3_fu_388_p2;
    D_3_we0 <= D_3_we0_local;

    D_3_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            D_3_we0_local <= ap_const_logic_1;
        else 
            D_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    E_0_address0 <= zext_ln117_reg_516(4 - 1 downto 0);
    E_0_ce0 <= E_0_ce0_local;

    E_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            E_0_ce0_local <= ap_const_logic_1;
        else 
            E_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    E_0_d0 <= mul_ln125_fu_359_p2;
    E_0_we0 <= E_0_we0_local;

    E_0_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            E_0_we0_local <= ap_const_logic_1;
        else 
            E_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    E_1_address0 <= zext_ln117_reg_516(4 - 1 downto 0);
    E_1_ce0 <= E_1_ce0_local;

    E_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            E_1_ce0_local <= ap_const_logic_1;
        else 
            E_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    E_1_d0 <= mul_ln125_1_fu_371_p2;
    E_1_we0 <= E_1_we0_local;

    E_1_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            E_1_we0_local <= ap_const_logic_1;
        else 
            E_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    E_2_address0 <= zext_ln117_reg_516(4 - 1 downto 0);
    E_2_ce0 <= E_2_ce0_local;

    E_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            E_2_ce0_local <= ap_const_logic_1;
        else 
            E_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    E_2_d0 <= mul_ln125_2_fu_383_p2;
    E_2_we0 <= E_2_we0_local;

    E_2_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            E_2_we0_local <= ap_const_logic_1;
        else 
            E_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    E_3_address0 <= zext_ln117_reg_516(4 - 1 downto 0);
    E_3_ce0 <= E_3_ce0_local;

    E_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            E_3_ce0_local <= ap_const_logic_1;
        else 
            E_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    E_3_d0 <= mul_ln125_3_fu_395_p2;
    E_3_we0 <= E_3_we0_local;

    E_3_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            E_3_we0_local <= ap_const_logic_1;
        else 
            E_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_263_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_263 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, tmp_fu_436_p3)
    begin
        if (((tmp_fu_436_p3 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    ap_sig_allocacmp_i1_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, i1_fu_88, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i1_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_i1_load <= i1_fu_88;
        end if; 
    end process;

    diff_3_fu_502_p0 <= A_3_q0;
    diff_3_fu_502_p1 <= B_3_q0;
    diff_4_fu_472_p0 <= A_1_q0;
    diff_4_fu_472_p1 <= B_1_q0;
    diff_5_fu_487_p0 <= A_2_q0;
    diff_5_fu_487_p1 <= B_2_q0;
    diff_fu_457_p0 <= A_0_q0;
    diff_fu_457_p1 <= B_0_q0;
    i_fu_430_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i1_load) + unsigned(ap_const_lv7_4));
    lshr_ln_fu_408_p4 <= ap_sig_allocacmp_i1_load(5 downto 2);
    mul_ln125_1_fu_371_p1 <= std_logic_vector(signed(diff_4_fu_472_p0) - signed(diff_4_fu_472_p1));
    mul_ln125_2_fu_383_p1 <= std_logic_vector(signed(diff_5_fu_487_p0) - signed(diff_5_fu_487_p1));
    mul_ln125_3_fu_395_p1 <= std_logic_vector(signed(diff_3_fu_502_p0) - signed(diff_3_fu_502_p1));
    mul_ln125_fu_359_p1 <= std_logic_vector(signed(diff_fu_457_p0) - signed(diff_fu_457_p1));
    sum_3_fu_494_p0 <= B_3_q0;
    sum_3_fu_494_p1 <= A_3_q0;
    sum_3_fu_494_p2 <= std_logic_vector(signed(sum_3_fu_494_p0) + signed(sum_3_fu_494_p1));
    sum_4_fu_464_p0 <= B_1_q0;
    sum_4_fu_464_p1 <= A_1_q0;
    sum_4_fu_464_p2 <= std_logic_vector(signed(sum_4_fu_464_p0) + signed(sum_4_fu_464_p1));
    sum_5_fu_479_p0 <= B_2_q0;
    sum_5_fu_479_p1 <= A_2_q0;
    sum_5_fu_479_p2 <= std_logic_vector(signed(sum_5_fu_479_p0) + signed(sum_5_fu_479_p1));
    sum_fu_449_p0 <= B_0_q0;
    sum_fu_449_p1 <= A_0_q0;
    sum_fu_449_p2 <= std_logic_vector(signed(sum_fu_449_p0) + signed(sum_fu_449_p1));
    tmp_fu_436_p3 <= i_fu_430_p2(6 downto 6);
    zext_ln117_fu_418_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_408_p4),64));
end behav;
