// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sorter_sorter,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu13p-fsga2577-2-e,HLS_INPUT_CLOCK=25.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.278000,HLS_SYN_LAT=301,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=35,HLS_SYN_LUT=206,HLS_VERSION=2024_1}" *)

module sorter (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_address0,
        a_ce0,
        a_we0,
        a_d0,
        a_q0,
        a_address1,
        a_ce1,
        a_we1,
        a_d1,
        a_q1
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] a_address0;
output   a_ce0;
output   a_we0;
output  [31:0] a_d0;
input  [31:0] a_q0;
output  [3:0] a_address1;
output   a_ce1;
output   a_we1;
output  [31:0] a_d1;
input  [31:0] a_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [3:0] indvars_iv6_load_reg_113;
wire    ap_CS_fsm_state2;
wire    grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_ap_start;
wire    grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_ap_done;
wire    grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_ap_idle;
wire    grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_ap_ready;
wire   [3:0] grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_a_address0;
wire    grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_a_ce0;
wire    grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_a_we0;
wire   [31:0] grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_a_d0;
wire   [3:0] grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_a_address1;
wire    grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_a_ce1;
wire    grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_a_we1;
wire   [31:0] grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_a_d1;
reg    grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_ap_start_reg;
wire   [0:0] icmp_ln5_fu_64_p2;
wire    ap_CS_fsm_state3;
reg   [3:0] i_fu_36;
wire   [3:0] i_2_fu_70_p2;
reg   [3:0] indvars_iv6_fu_40;
wire   [3:0] add_ln5_fu_80_p2;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_ap_start_reg = 1'b0;
#0 i_fu_36 = 4'd0;
#0 indvars_iv6_fu_40 = 4'd0;
end

sorter_sorter_Pipeline_VITIS_LOOP_6_2 grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_ap_start),
    .ap_done(grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_ap_done),
    .ap_idle(grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_ap_idle),
    .ap_ready(grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_ap_ready),
    .indvars_iv6(indvars_iv6_load_reg_113),
    .a_address0(grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_a_address0),
    .a_ce0(grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_a_ce0),
    .a_we0(grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_a_we0),
    .a_d0(grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_a_d0),
    .a_q0(a_q0),
    .a_address1(grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_a_address1),
    .a_ce1(grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_a_ce1),
    .a_we1(grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_a_we1),
    .a_d1(grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_a_d1),
    .a_q1(a_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln5_fu_64_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_ap_start_reg <= 1'b1;
        end else if ((grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_ap_ready == 1'b1)) begin
            grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_36 <= 4'd0;
    end else if (((icmp_ln5_fu_64_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_fu_36 <= i_2_fu_70_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvars_iv6_fu_40 <= 4'd15;
    end else if (((icmp_ln5_fu_64_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        indvars_iv6_fu_40 <= add_ln5_fu_80_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        indvars_iv6_load_reg_113 <= indvars_iv6_fu_40;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln5_fu_64_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln5_fu_64_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln5_fu_64_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_address0 = grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_a_address0;

assign a_address1 = grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_a_address1;

assign a_ce0 = grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_a_ce0;

assign a_ce1 = grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_a_ce1;

assign a_d0 = grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_a_d0;

assign a_d1 = grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_a_d1;

assign a_we0 = grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_a_we0;

assign a_we1 = grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_a_we1;

assign add_ln5_fu_80_p2 = ($signed(indvars_iv6_fu_40) + $signed(4'd15));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_ap_start = grp_sorter_Pipeline_VITIS_LOOP_6_2_fu_44_ap_start_reg;

assign i_2_fu_70_p2 = (i_fu_36 + 4'd1);

assign icmp_ln5_fu_64_p2 = ((i_fu_36 == 4'd15) ? 1'b1 : 1'b0);

endmodule //sorter
