-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dense_optimized is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x_0_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    x_0_EN_A : OUT STD_LOGIC;
    x_0_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    x_0_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    x_0_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    x_0_Clk_A : OUT STD_LOGIC;
    x_0_Rst_A : OUT STD_LOGIC;
    x_1_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    x_1_EN_A : OUT STD_LOGIC;
    x_1_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    x_1_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    x_1_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    x_1_Clk_A : OUT STD_LOGIC;
    x_1_Rst_A : OUT STD_LOGIC;
    x_2_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    x_2_EN_A : OUT STD_LOGIC;
    x_2_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    x_2_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    x_2_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    x_2_Clk_A : OUT STD_LOGIC;
    x_2_Rst_A : OUT STD_LOGIC;
    x_3_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    x_3_EN_A : OUT STD_LOGIC;
    x_3_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    x_3_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    x_3_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    x_3_Clk_A : OUT STD_LOGIC;
    x_3_Rst_A : OUT STD_LOGIC;
    w_0_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_0_EN_A : OUT STD_LOGIC;
    w_0_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    w_0_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_0_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    w_0_Clk_A : OUT STD_LOGIC;
    w_0_Rst_A : OUT STD_LOGIC;
    w_1_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_1_EN_A : OUT STD_LOGIC;
    w_1_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    w_1_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_1_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    w_1_Clk_A : OUT STD_LOGIC;
    w_1_Rst_A : OUT STD_LOGIC;
    w_2_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_2_EN_A : OUT STD_LOGIC;
    w_2_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    w_2_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_2_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    w_2_Clk_A : OUT STD_LOGIC;
    w_2_Rst_A : OUT STD_LOGIC;
    w_3_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_3_EN_A : OUT STD_LOGIC;
    w_3_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    w_3_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_3_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    w_3_Clk_A : OUT STD_LOGIC;
    w_3_Rst_A : OUT STD_LOGIC;
    y_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    y_EN_A : OUT STD_LOGIC;
    y_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    y_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    y_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    y_Clk_A : OUT STD_LOGIC;
    y_Rst_A : OUT STD_LOGIC );
end;


architecture behav of dense_optimized is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "dense_optimized_dense_optimized,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu13p-fsga2577-2-e,HLS_INPUT_CLOCK=25.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.900714,HLS_SYN_LAT=130,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=60,HLS_SYN_LUT=333,HLS_VERSION=2024_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv7_7F : STD_LOGIC_VECTOR (6 downto 0) := "1111111";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln35_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal icmp_ln385_reg_230 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln38_fu_324_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln38_reg_506 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln38_fu_374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_552 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_addr_reg_557 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln35_reg_562 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_icmp_ln385_phi_fu_233_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln40_fu_360_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln36_fu_338_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln35_fu_315_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal indvar_flatten1_fu_98 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln35_1_fu_380_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_indvar_flatten1_load : STD_LOGIC_VECTOR (6 downto 0);
    signal j2_fu_102 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal j_fu_307_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_j2_load : STD_LOGIC_VECTOR (3 downto 0);
    signal i3_fu_106 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal i_fu_368_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_i3_load : STD_LOGIC_VECTOR (4 downto 0);
    signal sum4_fu_110 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal sum_fu_466_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_0_EN_A_local : STD_LOGIC;
    signal x_0_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal x_1_EN_A_local : STD_LOGIC;
    signal x_1_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal x_2_EN_A_local : STD_LOGIC;
    signal x_2_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal x_3_EN_A_local : STD_LOGIC;
    signal x_3_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal w_0_EN_A_local : STD_LOGIC;
    signal w_0_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal w_1_EN_A_local : STD_LOGIC;
    signal w_1_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal w_2_EN_A_local : STD_LOGIC;
    signal w_2_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal w_3_EN_A_local : STD_LOGIC;
    signal w_3_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal y_WEN_A_local : STD_LOGIC_VECTOR (3 downto 0);
    signal y_EN_A_local : STD_LOGIC;
    signal y_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_442_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_418_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln35_fu_293_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln35_fu_299_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal lshr_ln_fu_328_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_346_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln38_fu_320_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln40_fu_354_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_fu_418_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_442_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln40_fu_242_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln35_1_fu_410_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_399 : BOOLEAN;
    signal ap_condition_160 : BOOLEAN;
    signal ap_condition_406 : BOOLEAN;
    signal tmp_fu_418_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_418_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_418_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_418_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_442_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_442_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_442_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_442_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component dense_optimized_mul_32s_32s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component dense_optimized_sparsemux_9_2_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component dense_optimized_flow_control_loop_delay_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_loop_exit_ready_delayed : IN STD_LOGIC );
    end component;



begin
    mul_32s_32s_32_1_1_U1 : component dense_optimized_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => tmp_1_fu_442_p11,
        din1 => tmp_fu_418_p11,
        dout => mul_ln40_fu_242_p2);

    sparsemux_9_2_32_1_1_U2 : component dense_optimized_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => x_0_Dout_A,
        din1 => x_1_Dout_A,
        din2 => x_2_Dout_A,
        din3 => x_3_Dout_A,
        def => tmp_fu_418_p9,
        sel => trunc_ln38_reg_506,
        dout => tmp_fu_418_p11);

    sparsemux_9_2_32_1_1_U3 : component dense_optimized_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => w_0_Dout_A,
        din1 => w_1_Dout_A,
        din2 => w_2_Dout_A,
        din3 => w_3_Dout_A,
        def => tmp_1_fu_442_p9,
        sel => trunc_ln38_reg_506,
        dout => tmp_1_fu_442_p11);

    flow_control_loop_delay_pipe_U : component dense_optimized_flow_control_loop_delay_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_const_logic_1,
        ap_loop_exit_ready_delayed => ap_loop_exit_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if (((ap_loop_exit_ready = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
                    ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                end if;
            end if; 
        end if;
    end process;

    i3_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_160)) then
                i3_fu_106 <= i_fu_368_p2;
            end if;
        end if;
    end process;

    icmp_ln385_reg_230_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if ((ap_const_boolean_1 = ap_condition_406)) then 
                    icmp_ln385_reg_230 <= icmp_ln38_reg_552;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_init = ap_const_logic_1))) then 
                    icmp_ln385_reg_230 <= ap_const_lv1_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten1_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_160)) then
                indvar_flatten1_fu_98 <= add_ln35_1_fu_380_p2;
            end if;
        end if;
    end process;

    j2_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_160)) then
                j2_fu_102 <= j_fu_307_p3;
            end if;
        end if;
    end process;

    sum4_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1))) then 
                    sum4_fu_110 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    sum4_fu_110 <= sum_fu_466_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln35_reg_562 <= icmp_ln35_fu_386_p2;
                trunc_ln38_reg_506 <= trunc_ln38_fu_324_p1;
                y_addr_reg_557 <= zext_ln35_fu_315_p1(3 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln38_reg_552 <= icmp_ln38_fu_374_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln35_1_fu_380_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten1_load) + unsigned(ap_const_lv7_1));
    add_ln35_fu_293_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j2_load) + unsigned(ap_const_lv4_1));
    add_ln40_fu_354_p2 <= std_logic_vector(unsigned(tmp_2_fu_346_p3) + unsigned(zext_ln38_fu_320_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_160_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_160 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_399_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln35_reg_562, ap_block_pp0_stage0)
    begin
                ap_condition_399 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln35_reg_562 = ap_const_lv1_0));
    end process;


    ap_condition_406_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln35_reg_562)
    begin
                ap_condition_406 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln35_reg_562 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln35_fu_386_p2)
    begin
        if (((icmp_ln35_fu_386_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_loop_exit_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_loop_exit_done_int <= ap_const_logic_1;
        else 
            ap_loop_exit_done_int <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_icmp_ln385_phi_fu_233_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln38_reg_552, ap_loop_init, ap_condition_399)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
            if ((ap_const_boolean_1 = ap_condition_399)) then 
                ap_phi_mux_icmp_ln385_phi_fu_233_p4 <= icmp_ln38_reg_552;
            elsif ((ap_loop_init = ap_const_logic_1)) then 
                ap_phi_mux_icmp_ln385_phi_fu_233_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_icmp_ln385_phi_fu_233_p4 <= icmp_ln38_reg_552;
            end if;
        else 
            ap_phi_mux_icmp_ln385_phi_fu_233_p4 <= icmp_ln38_reg_552;
        end if; 
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i3_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_loop_init, ap_block_pp0_stage0, i3_fu_106)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i3_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_i3_load <= i3_fu_106;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten1_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_loop_init, ap_block_pp0_stage0, indvar_flatten1_fu_98)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten1_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_indvar_flatten1_load <= indvar_flatten1_fu_98;
        end if; 
    end process;


    ap_sig_allocacmp_j2_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_loop_init, ap_block_pp0_stage0, j2_fu_102)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j2_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_j2_load <= j2_fu_102;
        end if; 
    end process;

    i_fu_368_p2 <= std_logic_vector(unsigned(select_ln35_fu_299_p3) + unsigned(ap_const_lv5_1));
    icmp_ln35_fu_386_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten1_load = ap_const_lv7_7F) else "0";
    icmp_ln38_fu_374_p2 <= "1" when (i_fu_368_p2 = ap_const_lv5_10) else "0";
    j_fu_307_p3 <= 
        add_ln35_fu_293_p2 when (ap_phi_mux_icmp_ln385_phi_fu_233_p4(0) = '1') else 
        ap_sig_allocacmp_j2_load;
    lshr_ln_fu_328_p4 <= select_ln35_fu_299_p3(3 downto 2);
    select_ln35_1_fu_410_p3 <= 
        ap_const_lv32_0 when (icmp_ln385_reg_230(0) = '1') else 
        sum4_fu_110;
    select_ln35_fu_299_p3 <= 
        ap_const_lv5_0 when (ap_phi_mux_icmp_ln385_phi_fu_233_p4(0) = '1') else 
        ap_sig_allocacmp_i3_load;
    sum_fu_466_p2 <= std_logic_vector(unsigned(mul_ln40_fu_242_p2) + unsigned(select_ln35_1_fu_410_p3));
    tmp_1_fu_442_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_2_fu_346_p3 <= (lshr_ln_fu_328_p4 & ap_const_lv3_0);
    tmp_fu_418_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    trunc_ln38_fu_324_p1 <= select_ln35_fu_299_p3(2 - 1 downto 0);
    w_0_Addr_A <= std_logic_vector(shift_left(unsigned(w_0_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    w_0_Addr_A_orig <= zext_ln40_fu_360_p1(32 - 1 downto 0);
    w_0_Clk_A <= ap_clk;
    w_0_Din_A <= ap_const_lv32_0;
    w_0_EN_A <= w_0_EN_A_local;

    w_0_EN_A_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            w_0_EN_A_local <= ap_const_logic_1;
        else 
            w_0_EN_A_local <= ap_const_logic_0;
        end if; 
    end process;

    w_0_Rst_A <= ap_rst;
    w_0_WEN_A <= ap_const_lv4_0;
    w_1_Addr_A <= std_logic_vector(shift_left(unsigned(w_1_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    w_1_Addr_A_orig <= zext_ln40_fu_360_p1(32 - 1 downto 0);
    w_1_Clk_A <= ap_clk;
    w_1_Din_A <= ap_const_lv32_0;
    w_1_EN_A <= w_1_EN_A_local;

    w_1_EN_A_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            w_1_EN_A_local <= ap_const_logic_1;
        else 
            w_1_EN_A_local <= ap_const_logic_0;
        end if; 
    end process;

    w_1_Rst_A <= ap_rst;
    w_1_WEN_A <= ap_const_lv4_0;
    w_2_Addr_A <= std_logic_vector(shift_left(unsigned(w_2_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    w_2_Addr_A_orig <= zext_ln40_fu_360_p1(32 - 1 downto 0);
    w_2_Clk_A <= ap_clk;
    w_2_Din_A <= ap_const_lv32_0;
    w_2_EN_A <= w_2_EN_A_local;

    w_2_EN_A_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            w_2_EN_A_local <= ap_const_logic_1;
        else 
            w_2_EN_A_local <= ap_const_logic_0;
        end if; 
    end process;

    w_2_Rst_A <= ap_rst;
    w_2_WEN_A <= ap_const_lv4_0;
    w_3_Addr_A <= std_logic_vector(shift_left(unsigned(w_3_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    w_3_Addr_A_orig <= zext_ln40_fu_360_p1(32 - 1 downto 0);
    w_3_Clk_A <= ap_clk;
    w_3_Din_A <= ap_const_lv32_0;
    w_3_EN_A <= w_3_EN_A_local;

    w_3_EN_A_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            w_3_EN_A_local <= ap_const_logic_1;
        else 
            w_3_EN_A_local <= ap_const_logic_0;
        end if; 
    end process;

    w_3_Rst_A <= ap_rst;
    w_3_WEN_A <= ap_const_lv4_0;
    x_0_Addr_A <= std_logic_vector(shift_left(unsigned(x_0_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    x_0_Addr_A_orig <= zext_ln36_fu_338_p1(32 - 1 downto 0);
    x_0_Clk_A <= ap_clk;
    x_0_Din_A <= ap_const_lv32_0;
    x_0_EN_A <= x_0_EN_A_local;

    x_0_EN_A_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_0_EN_A_local <= ap_const_logic_1;
        else 
            x_0_EN_A_local <= ap_const_logic_0;
        end if; 
    end process;

    x_0_Rst_A <= ap_rst;
    x_0_WEN_A <= ap_const_lv4_0;
    x_1_Addr_A <= std_logic_vector(shift_left(unsigned(x_1_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    x_1_Addr_A_orig <= zext_ln36_fu_338_p1(32 - 1 downto 0);
    x_1_Clk_A <= ap_clk;
    x_1_Din_A <= ap_const_lv32_0;
    x_1_EN_A <= x_1_EN_A_local;

    x_1_EN_A_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_1_EN_A_local <= ap_const_logic_1;
        else 
            x_1_EN_A_local <= ap_const_logic_0;
        end if; 
    end process;

    x_1_Rst_A <= ap_rst;
    x_1_WEN_A <= ap_const_lv4_0;
    x_2_Addr_A <= std_logic_vector(shift_left(unsigned(x_2_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    x_2_Addr_A_orig <= zext_ln36_fu_338_p1(32 - 1 downto 0);
    x_2_Clk_A <= ap_clk;
    x_2_Din_A <= ap_const_lv32_0;
    x_2_EN_A <= x_2_EN_A_local;

    x_2_EN_A_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_2_EN_A_local <= ap_const_logic_1;
        else 
            x_2_EN_A_local <= ap_const_logic_0;
        end if; 
    end process;

    x_2_Rst_A <= ap_rst;
    x_2_WEN_A <= ap_const_lv4_0;
    x_3_Addr_A <= std_logic_vector(shift_left(unsigned(x_3_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    x_3_Addr_A_orig <= zext_ln36_fu_338_p1(32 - 1 downto 0);
    x_3_Clk_A <= ap_clk;
    x_3_Din_A <= ap_const_lv32_0;
    x_3_EN_A <= x_3_EN_A_local;

    x_3_EN_A_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_3_EN_A_local <= ap_const_logic_1;
        else 
            x_3_EN_A_local <= ap_const_logic_0;
        end if; 
    end process;

    x_3_Rst_A <= ap_rst;
    x_3_WEN_A <= ap_const_lv4_0;
    y_Addr_A <= std_logic_vector(shift_left(unsigned(y_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    y_Addr_A_orig <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_addr_reg_557),32));
    y_Clk_A <= ap_clk;
    y_Din_A <= sum_fu_466_p2;
    y_EN_A <= y_EN_A_local;

    y_EN_A_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            y_EN_A_local <= ap_const_logic_1;
        else 
            y_EN_A_local <= ap_const_logic_0;
        end if; 
    end process;

    y_Rst_A <= ap_rst;
    y_WEN_A <= y_WEN_A_local;

    y_WEN_A_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln38_reg_552)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln38_reg_552 = ap_const_lv1_1))) then 
            y_WEN_A_local <= ap_const_lv4_F;
        else 
            y_WEN_A_local <= ap_const_lv4_0;
        end if; 
    end process;

    zext_ln35_fu_315_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_fu_307_p3),64));
    zext_ln36_fu_338_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_328_p4),64));
    zext_ln38_fu_320_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_fu_307_p3),5));
    zext_ln40_fu_360_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln40_fu_354_p2),64));
end behav;
