#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("A_address0", 6, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("A_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("A_q0", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("B_address0", 6, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("B_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("B_q0", 32, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("C_address0", 6, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("C_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("C_we0", 1, hls_out, 2, "ap_memory", "mem_we", 1),
	Port_Property("C_d0", 32, hls_out, 2, "ap_memory", "mem_din", 1),
	Port_Property("D_address0", 6, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("D_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("D_we0", 1, hls_out, 3, "ap_memory", "mem_we", 1),
	Port_Property("D_d0", 32, hls_out, 3, "ap_memory", "mem_din", 1),
	Port_Property("E_address0", 6, hls_out, 4, "ap_memory", "mem_address", 1),
	Port_Property("E_ce0", 1, hls_out, 4, "ap_memory", "mem_ce", 1),
	Port_Property("E_we0", 1, hls_out, 4, "ap_memory", "mem_we", 1),
	Port_Property("E_d0", 32, hls_out, 4, "ap_memory", "mem_din", 1),
	Port_Property("s_axi_control_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_AWADDR", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_ARADDR", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("interrupt", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "q5_interface";
