// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module dense_simple_dense_simple_Pipeline_VITIS_LOOP_8_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        w_address0,
        w_ce0,
        w_q0,
        w_address1,
        w_ce1,
        w_q1,
        x_load_7,
        x_load_11,
        x_load_8,
        x_load_2,
        x_load_1,
        x_load_5,
        x_load_12,
        x_load_3,
        x_load_10,
        x_load_4,
        x_load_13,
        x_load_6,
        x_load,
        x_load_14,
        x_load_9,
        x_load_15,
        y_address0,
        y_ce0,
        y_we0,
        y_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 8'd1;
parameter    ap_ST_fsm_pp0_stage1 = 8'd2;
parameter    ap_ST_fsm_pp0_stage2 = 8'd4;
parameter    ap_ST_fsm_pp0_stage3 = 8'd8;
parameter    ap_ST_fsm_pp0_stage4 = 8'd16;
parameter    ap_ST_fsm_pp0_stage5 = 8'd32;
parameter    ap_ST_fsm_pp0_stage6 = 8'd64;
parameter    ap_ST_fsm_pp0_stage7 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] w_address0;
output   w_ce0;
input  [31:0] w_q0;
output  [6:0] w_address1;
output   w_ce1;
input  [31:0] w_q1;
input  [31:0] x_load_7;
input  [31:0] x_load_11;
input  [31:0] x_load_8;
input  [31:0] x_load_2;
input  [31:0] x_load_1;
input  [31:0] x_load_5;
input  [31:0] x_load_12;
input  [31:0] x_load_3;
input  [31:0] x_load_10;
input  [31:0] x_load_4;
input  [31:0] x_load_13;
input  [31:0] x_load_6;
input  [31:0] x_load;
input  [31:0] x_load_14;
input  [31:0] x_load_9;
input  [31:0] x_load_15;
output  [2:0] y_address0;
output   y_ce0;
output   y_we0;
output  [31:0] y_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7_subdone;
reg   [0:0] icmp_ln8_reg_731;
reg    ap_condition_exit_pp0_iter0_stage7;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [31:0] grp_fu_340_p2;
reg   [31:0] reg_364;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_11001;
wire    ap_block_pp0_stage7_11001;
wire   [31:0] grp_fu_345_p2;
reg   [31:0] reg_368;
wire    ap_block_pp0_stage0_11001;
reg   [2:0] j1_load_reg_699;
wire   [63:0] zext_ln8_fu_392_p1;
reg   [63:0] zext_ln8_reg_709;
wire  signed [3:0] add_ln12_s_fu_397_p3;
reg  signed [3:0] add_ln12_s_reg_719;
wire   [0:0] icmp_ln8_fu_416_p2;
wire   [3:0] zext_ln8_1_fu_427_p1;
reg   [3:0] zext_ln8_1_reg_735;
wire  signed [4:0] tmp_cast_fu_430_p3;
reg  signed [4:0] tmp_cast_reg_740;
wire  signed [5:0] tmp_1_cast_fu_454_p3;
reg  signed [5:0] tmp_1_cast_reg_756;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
wire  signed [5:0] add_ln12_14_fu_467_p3;
reg  signed [5:0] add_ln12_14_reg_766;
wire   [31:0] grp_fu_378_p2;
reg   [31:0] add_ln12_2_reg_776;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_11001;
wire   [31:0] add_ln12_5_fu_529_p2;
reg   [31:0] add_ln12_5_reg_801;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5_11001;
wire   [31:0] grp_fu_352_p2;
reg   [31:0] add_ln12_7_reg_816;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6_11001;
wire   [31:0] grp_fu_358_p2;
reg   [31:0] add_ln12_8_reg_831;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln12_2_fu_405_p1;
wire   [63:0] zext_ln12_3_fu_438_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln12_4_fu_446_p1;
wire   [63:0] zext_ln12_5_fu_462_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln12_6_fu_474_p1;
wire   [63:0] zext_ln12_7_fu_482_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] zext_ln12_8_fu_490_p1;
wire   [63:0] zext_ln12_9_fu_506_p1;
wire    ap_block_pp0_stage4;
wire   [63:0] zext_ln12_10_fu_518_p1;
wire   [63:0] zext_ln12_11_fu_542_p1;
wire    ap_block_pp0_stage5;
wire   [63:0] zext_ln12_12_fu_554_p1;
wire   [63:0] zext_ln12_13_fu_562_p1;
wire    ap_block_pp0_stage6;
wire   [63:0] zext_ln12_14_fu_570_p1;
wire   [63:0] zext_ln12_15_fu_578_p1;
wire    ap_block_pp0_stage7;
wire   [63:0] zext_ln12_16_fu_586_p1;
reg   [2:0] j1_fu_90;
wire   [2:0] j_fu_410_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_j1_load;
reg    w_ce1_local;
reg   [6:0] w_address1_local;
reg    w_ce0_local;
reg   [6:0] w_address0_local;
reg    y_we0_local;
wire   [31:0] sum_fu_605_p2;
reg    y_ce0_local;
reg  signed [31:0] grp_fu_340_p0;
reg  signed [31:0] grp_fu_340_p1;
reg  signed [31:0] grp_fu_345_p0;
reg  signed [31:0] grp_fu_345_p1;
wire   [31:0] grp_fu_372_p2;
wire  signed [4:0] sext_ln12_fu_443_p1;
wire   [4:0] zext_ln12_fu_451_p1;
wire  signed [5:0] sext_ln12_1_fu_479_p1;
wire  signed [5:0] sext_ln12_2_fu_487_p1;
wire   [5:0] zext_ln12_1_fu_495_p1;
wire   [6:0] tmp_3_cast_fu_498_p3;
wire   [6:0] add_ln12_15_fu_511_p3;
wire   [31:0] add_ln12_3_fu_523_p2;
wire   [6:0] tmp_4_cast_fu_535_p3;
wire   [6:0] add_ln12_16_fu_547_p3;
wire  signed [6:0] sext_ln12_3_fu_559_p1;
wire  signed [6:0] sext_ln12_4_fu_567_p1;
wire  signed [6:0] sext_ln12_5_fu_575_p1;
wire  signed [6:0] sext_ln12_6_fu_583_p1;
wire   [31:0] add_ln12_9_fu_595_p2;
wire   [31:0] add_ln12_13_fu_599_p2;
wire   [31:0] add_ln12_6_fu_591_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter1_stage0;
reg    ap_idle_pp0_0to0;
reg   [7:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 j1_fu_90 = 3'd0;
#0 ap_done_reg = 1'b0;
end

dense_simple_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U1(
    .din0(grp_fu_340_p0),
    .din1(grp_fu_340_p1),
    .dout(grp_fu_340_p2)
);

dense_simple_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U2(
    .din0(grp_fu_345_p0),
    .din1(grp_fu_345_p1),
    .dout(grp_fu_345_p2)
);

dense_simple_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage7),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage0)))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
            j1_fu_90 <= j_fu_410_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j1_fu_90 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln12_14_reg_766[2 : 0] <= add_ln12_14_fu_467_p3[2 : 0];
        tmp_1_cast_reg_756[2 : 0] <= tmp_1_cast_fu_454_p3[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln12_2_reg_776 <= grp_fu_378_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        add_ln12_5_reg_801 <= add_ln12_5_fu_529_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        add_ln12_7_reg_816 <= grp_fu_352_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        add_ln12_8_reg_831 <= grp_fu_358_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln12_s_reg_719[2 : 0] <= add_ln12_s_fu_397_p3[2 : 0];
        icmp_ln8_reg_731 <= icmp_ln8_fu_416_p2;
        j1_load_reg_699 <= ap_sig_allocacmp_j1_load;
        zext_ln8_reg_709[2 : 0] <= zext_ln8_fu_392_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        reg_364 <= grp_fu_340_p2;
        reg_368 <= grp_fu_345_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_cast_reg_740[2 : 0] <= tmp_cast_fu_430_p3[2 : 0];
        zext_ln8_1_reg_735[2 : 0] <= zext_ln8_1_fu_427_p1[2 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln8_reg_731 == 1'd1) & (1'b0 == ap_block_pp0_stage7_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_condition_exit_pp0_iter0_stage7 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage7 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln8_reg_731 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage7_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j1_load = 3'd0;
    end else begin
        ap_sig_allocacmp_j1_load = j1_fu_90;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_340_p0 = w_q1;
    end else if ((((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_340_p0 = w_q0;
    end else begin
        grp_fu_340_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_340_p1 = x_load_14;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_340_p1 = x_load_12;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_340_p1 = x_load_11;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_340_p1 = x_load_8;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_340_p1 = x_load_7;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_340_p1 = x_load_5;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_340_p1 = x_load_2;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_340_p1 = x_load_1;
    end else begin
        grp_fu_340_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_345_p0 = w_q0;
    end else if ((((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_345_p0 = w_q1;
    end else begin
        grp_fu_345_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_345_p1 = x_load_15;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_345_p1 = x_load_13;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_345_p1 = x_load_10;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_345_p1 = x_load_9;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_345_p1 = x_load_6;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_345_p1 = x_load_4;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_345_p1 = x_load_3;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_345_p1 = x_load;
    end else begin
        grp_fu_345_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            w_address0_local = zext_ln12_16_fu_586_p1;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            w_address0_local = zext_ln12_14_fu_570_p1;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            w_address0_local = zext_ln12_12_fu_554_p1;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            w_address0_local = zext_ln12_10_fu_518_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            w_address0_local = zext_ln12_8_fu_490_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            w_address0_local = zext_ln12_6_fu_474_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            w_address0_local = zext_ln12_4_fu_446_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            w_address0_local = zext_ln12_2_fu_405_p1;
        end else begin
            w_address0_local = 'bx;
        end
    end else begin
        w_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            w_address1_local = zext_ln12_15_fu_578_p1;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            w_address1_local = zext_ln12_13_fu_562_p1;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            w_address1_local = zext_ln12_11_fu_542_p1;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            w_address1_local = zext_ln12_9_fu_506_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            w_address1_local = zext_ln12_7_fu_482_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            w_address1_local = zext_ln12_5_fu_462_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            w_address1_local = zext_ln12_3_fu_438_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            w_address1_local = zext_ln8_fu_392_p1;
        end else begin
            w_address1_local = 'bx;
        end
    end else begin
        w_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        w_ce0_local = 1'b1;
    end else begin
        w_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        w_ce1_local = 1'b1;
    end else begin
        w_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        y_ce0_local = 1'b1;
    end else begin
        y_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        y_we0_local = 1'b1;
    end else begin
        y_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln12_13_fu_599_p2 = (grp_fu_378_p2 + add_ln12_9_fu_595_p2);

assign add_ln12_14_fu_467_p3 = {{3'd5}, {j1_load_reg_699}};

assign add_ln12_15_fu_511_p3 = {{4'd9}, {j1_load_reg_699}};

assign add_ln12_16_fu_547_p3 = {{4'd11}, {j1_load_reg_699}};

assign add_ln12_3_fu_523_p2 = (reg_368 + reg_364);

assign add_ln12_5_fu_529_p2 = (grp_fu_358_p2 + add_ln12_3_fu_523_p2);

assign add_ln12_6_fu_591_p2 = (add_ln12_5_reg_801 + add_ln12_2_reg_776);

assign add_ln12_9_fu_595_p2 = (add_ln12_8_reg_831 + add_ln12_7_reg_816);

assign add_ln12_s_fu_397_p3 = {{1'd1}, {ap_sig_allocacmp_j1_load}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage7;

assign ap_ready = ap_ready_sig;

assign grp_fu_352_p2 = (grp_fu_340_p2 + grp_fu_345_p2);

assign grp_fu_358_p2 = (grp_fu_345_p2 + grp_fu_340_p2);

assign grp_fu_372_p2 = (reg_364 + reg_368);

assign grp_fu_378_p2 = (grp_fu_352_p2 + grp_fu_372_p2);

assign icmp_ln8_fu_416_p2 = ((ap_sig_allocacmp_j1_load == 3'd7) ? 1'b1 : 1'b0);

assign j_fu_410_p2 = (ap_sig_allocacmp_j1_load + 3'd1);

assign sext_ln12_1_fu_479_p1 = tmp_cast_reg_740;

assign sext_ln12_2_fu_487_p1 = add_ln12_s_reg_719;

assign sext_ln12_3_fu_559_p1 = tmp_1_cast_reg_756;

assign sext_ln12_4_fu_567_p1 = add_ln12_14_reg_766;

assign sext_ln12_5_fu_575_p1 = tmp_cast_reg_740;

assign sext_ln12_6_fu_583_p1 = add_ln12_s_reg_719;

assign sext_ln12_fu_443_p1 = add_ln12_s_reg_719;

assign sum_fu_605_p2 = (add_ln12_13_fu_599_p2 + add_ln12_6_fu_591_p2);

assign tmp_1_cast_fu_454_p3 = {{1'd1}, {zext_ln12_fu_451_p1}};

assign tmp_3_cast_fu_498_p3 = {{1'd1}, {zext_ln12_1_fu_495_p1}};

assign tmp_4_cast_fu_535_p3 = {{3'd5}, {zext_ln8_1_reg_735}};

assign tmp_cast_fu_430_p3 = {{1'd1}, {zext_ln8_1_fu_427_p1}};

assign w_address0 = w_address0_local;

assign w_address1 = w_address1_local;

assign w_ce0 = w_ce0_local;

assign w_ce1 = w_ce1_local;

assign y_address0 = zext_ln8_reg_709;

assign y_ce0 = y_ce0_local;

assign y_d0 = sum_fu_605_p2;

assign y_we0 = y_we0_local;

assign zext_ln12_10_fu_518_p1 = add_ln12_15_fu_511_p3;

assign zext_ln12_11_fu_542_p1 = tmp_4_cast_fu_535_p3;

assign zext_ln12_12_fu_554_p1 = add_ln12_16_fu_547_p3;

assign zext_ln12_13_fu_562_p1 = $unsigned(sext_ln12_3_fu_559_p1);

assign zext_ln12_14_fu_570_p1 = $unsigned(sext_ln12_4_fu_567_p1);

assign zext_ln12_15_fu_578_p1 = $unsigned(sext_ln12_5_fu_575_p1);

assign zext_ln12_16_fu_586_p1 = $unsigned(sext_ln12_6_fu_583_p1);

assign zext_ln12_1_fu_495_p1 = j1_load_reg_699;

assign zext_ln12_2_fu_405_p1 = $unsigned(add_ln12_s_fu_397_p3);

assign zext_ln12_3_fu_438_p1 = $unsigned(tmp_cast_fu_430_p3);

assign zext_ln12_4_fu_446_p1 = $unsigned(sext_ln12_fu_443_p1);

assign zext_ln12_5_fu_462_p1 = $unsigned(tmp_1_cast_fu_454_p3);

assign zext_ln12_6_fu_474_p1 = $unsigned(add_ln12_14_fu_467_p3);

assign zext_ln12_7_fu_482_p1 = $unsigned(sext_ln12_1_fu_479_p1);

assign zext_ln12_8_fu_490_p1 = $unsigned(sext_ln12_2_fu_487_p1);

assign zext_ln12_9_fu_506_p1 = tmp_3_cast_fu_498_p3;

assign zext_ln12_fu_451_p1 = j1_load_reg_699;

assign zext_ln8_1_fu_427_p1 = j1_load_reg_699;

assign zext_ln8_fu_392_p1 = ap_sig_allocacmp_j1_load;

always @ (posedge ap_clk) begin
    zext_ln8_reg_709[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    add_ln12_s_reg_719[3] <= 1'b1;
    zext_ln8_1_reg_735[3] <= 1'b0;
    tmp_cast_reg_740[4:3] <= 2'b10;
    tmp_1_cast_reg_756[5:3] <= 3'b100;
    add_ln12_14_reg_766[5:3] <= 3'b101;
end

endmodule //dense_simple_dense_simple_Pipeline_VITIS_LOOP_8_1
