// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "matrix_mult.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic matrix_mult::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic matrix_mult::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> matrix_mult::ap_ST_fsm_state1 = "1";
const sc_lv<5> matrix_mult::ap_ST_fsm_state2 = "10";
const sc_lv<5> matrix_mult::ap_ST_fsm_state3 = "100";
const sc_lv<5> matrix_mult::ap_ST_fsm_state4 = "1000";
const sc_lv<5> matrix_mult::ap_ST_fsm_state5 = "10000";
const sc_lv<32> matrix_mult::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> matrix_mult::ap_const_lv32_1 = "1";
const sc_lv<1> matrix_mult::ap_const_lv1_0 = "0";
const sc_lv<32> matrix_mult::ap_const_lv32_2 = "10";
const sc_lv<32> matrix_mult::ap_const_lv32_3 = "11";
const sc_lv<32> matrix_mult::ap_const_lv32_4 = "100";
const sc_lv<4> matrix_mult::ap_const_lv4_0 = "0000";
const sc_lv<1> matrix_mult::ap_const_lv1_1 = "1";
const sc_lv<4> matrix_mult::ap_const_lv4_A = "1010";
const sc_lv<4> matrix_mult::ap_const_lv4_1 = "1";
const sc_lv<3> matrix_mult::ap_const_lv3_0 = "000";
const bool matrix_mult::ap_const_boolean_1 = true;

matrix_mult::matrix_mult(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_A_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln10_3_fu_207_p1 );

    SC_METHOD(thread_A_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_B_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln10_6_fu_247_p1 );

    SC_METHOD(thread_B_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_C_address0);
    sensitive << ( C_addr_reg_291 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_C_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_C_d0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( C_load_reg_94 );

    SC_METHOD(thread_C_we0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_add_ln10_1_fu_154_p2);
    sensitive << ( zext_ln10_1_fu_150_p1 );
    sensitive << ( zext_ln10_fu_138_p1 );

    SC_METHOD(thread_add_ln10_2_fu_202_p2);
    sensitive << ( add_ln10_1_reg_272 );
    sensitive << ( zext_ln10_2_fu_198_p1 );

    SC_METHOD(thread_add_ln10_3_fu_236_p2);
    sensitive << ( zext_ln10_5_fu_232_p1 );
    sensitive << ( zext_ln10_4_fu_220_p1 );

    SC_METHOD(thread_add_ln10_4_fu_242_p2);
    sensitive << ( zext_ln8_reg_286 );
    sensitive << ( add_ln10_3_fu_236_p2 );

    SC_METHOD(thread_add_ln10_fu_258_p2);
    sensitive << ( C_load_reg_94 );
    sensitive << ( mul_ln10_fu_252_p2 );

    SC_METHOD(thread_add_ln8_fu_176_p2);
    sensitive << ( add_ln10_1_reg_272 );
    sensitive << ( zext_ln8_fu_172_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln6_fu_118_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln6_fu_118_p2 );

    SC_METHOD(thread_i_fu_124_p2);
    sensitive << ( i_0_reg_72 );

    SC_METHOD(thread_icmp_ln6_fu_118_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_72 );

    SC_METHOD(thread_icmp_ln7_fu_160_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( j_0_reg_83 );

    SC_METHOD(thread_icmp_ln9_fu_186_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( k_0_reg_107 );

    SC_METHOD(thread_j_fu_166_p2);
    sensitive << ( j_0_reg_83 );

    SC_METHOD(thread_k_fu_192_p2);
    sensitive << ( k_0_reg_107 );

    SC_METHOD(thread_mul_ln10_fu_252_p0);
    sensitive << ( B_q0 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mul_ln10_fu_252_p1);
    sensitive << ( A_q0 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mul_ln10_fu_252_p2);
    sensitive << ( mul_ln10_fu_252_p0 );
    sensitive << ( mul_ln10_fu_252_p1 );

    SC_METHOD(thread_tmp_1_fu_142_p3);
    sensitive << ( i_0_reg_72 );

    SC_METHOD(thread_tmp_2_fu_212_p3);
    sensitive << ( k_0_reg_107 );

    SC_METHOD(thread_tmp_3_fu_224_p3);
    sensitive << ( k_0_reg_107 );

    SC_METHOD(thread_tmp_fu_130_p3);
    sensitive << ( i_0_reg_72 );

    SC_METHOD(thread_zext_ln10_1_fu_150_p1);
    sensitive << ( tmp_1_fu_142_p3 );

    SC_METHOD(thread_zext_ln10_2_fu_198_p1);
    sensitive << ( k_0_reg_107 );

    SC_METHOD(thread_zext_ln10_3_fu_207_p1);
    sensitive << ( add_ln10_2_fu_202_p2 );

    SC_METHOD(thread_zext_ln10_4_fu_220_p1);
    sensitive << ( tmp_2_fu_212_p3 );

    SC_METHOD(thread_zext_ln10_5_fu_232_p1);
    sensitive << ( tmp_3_fu_224_p3 );

    SC_METHOD(thread_zext_ln10_6_fu_247_p1);
    sensitive << ( add_ln10_4_fu_242_p2 );

    SC_METHOD(thread_zext_ln10_fu_138_p1);
    sensitive << ( tmp_fu_130_p3 );

    SC_METHOD(thread_zext_ln8_1_fu_181_p1);
    sensitive << ( add_ln8_fu_176_p2 );

    SC_METHOD(thread_zext_ln8_fu_172_p1);
    sensitive << ( j_0_reg_83 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln6_fu_118_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln7_fu_160_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln9_fu_186_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "00001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "matrix_mult_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, A_address0, "(port)A_address0");
    sc_trace(mVcdFile, A_ce0, "(port)A_ce0");
    sc_trace(mVcdFile, A_q0, "(port)A_q0");
    sc_trace(mVcdFile, B_address0, "(port)B_address0");
    sc_trace(mVcdFile, B_ce0, "(port)B_ce0");
    sc_trace(mVcdFile, B_q0, "(port)B_q0");
    sc_trace(mVcdFile, C_address0, "(port)C_address0");
    sc_trace(mVcdFile, C_ce0, "(port)C_ce0");
    sc_trace(mVcdFile, C_we0, "(port)C_we0");
    sc_trace(mVcdFile, C_d0, "(port)C_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i_fu_124_p2, "i_fu_124_p2");
    sc_trace(mVcdFile, i_reg_267, "i_reg_267");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, add_ln10_1_fu_154_p2, "add_ln10_1_fu_154_p2");
    sc_trace(mVcdFile, add_ln10_1_reg_272, "add_ln10_1_reg_272");
    sc_trace(mVcdFile, icmp_ln6_fu_118_p2, "icmp_ln6_fu_118_p2");
    sc_trace(mVcdFile, j_fu_166_p2, "j_fu_166_p2");
    sc_trace(mVcdFile, j_reg_281, "j_reg_281");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, zext_ln8_fu_172_p1, "zext_ln8_fu_172_p1");
    sc_trace(mVcdFile, zext_ln8_reg_286, "zext_ln8_reg_286");
    sc_trace(mVcdFile, icmp_ln7_fu_160_p2, "icmp_ln7_fu_160_p2");
    sc_trace(mVcdFile, C_addr_reg_291, "C_addr_reg_291");
    sc_trace(mVcdFile, k_fu_192_p2, "k_fu_192_p2");
    sc_trace(mVcdFile, k_reg_299, "k_reg_299");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, icmp_ln9_fu_186_p2, "icmp_ln9_fu_186_p2");
    sc_trace(mVcdFile, add_ln10_fu_258_p2, "add_ln10_fu_258_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, i_0_reg_72, "i_0_reg_72");
    sc_trace(mVcdFile, j_0_reg_83, "j_0_reg_83");
    sc_trace(mVcdFile, C_load_reg_94, "C_load_reg_94");
    sc_trace(mVcdFile, k_0_reg_107, "k_0_reg_107");
    sc_trace(mVcdFile, zext_ln8_1_fu_181_p1, "zext_ln8_1_fu_181_p1");
    sc_trace(mVcdFile, zext_ln10_3_fu_207_p1, "zext_ln10_3_fu_207_p1");
    sc_trace(mVcdFile, zext_ln10_6_fu_247_p1, "zext_ln10_6_fu_247_p1");
    sc_trace(mVcdFile, tmp_fu_130_p3, "tmp_fu_130_p3");
    sc_trace(mVcdFile, tmp_1_fu_142_p3, "tmp_1_fu_142_p3");
    sc_trace(mVcdFile, zext_ln10_1_fu_150_p1, "zext_ln10_1_fu_150_p1");
    sc_trace(mVcdFile, zext_ln10_fu_138_p1, "zext_ln10_fu_138_p1");
    sc_trace(mVcdFile, add_ln8_fu_176_p2, "add_ln8_fu_176_p2");
    sc_trace(mVcdFile, zext_ln10_2_fu_198_p1, "zext_ln10_2_fu_198_p1");
    sc_trace(mVcdFile, add_ln10_2_fu_202_p2, "add_ln10_2_fu_202_p2");
    sc_trace(mVcdFile, tmp_2_fu_212_p3, "tmp_2_fu_212_p3");
    sc_trace(mVcdFile, tmp_3_fu_224_p3, "tmp_3_fu_224_p3");
    sc_trace(mVcdFile, zext_ln10_5_fu_232_p1, "zext_ln10_5_fu_232_p1");
    sc_trace(mVcdFile, zext_ln10_4_fu_220_p1, "zext_ln10_4_fu_220_p1");
    sc_trace(mVcdFile, add_ln10_3_fu_236_p2, "add_ln10_3_fu_236_p2");
    sc_trace(mVcdFile, add_ln10_4_fu_242_p2, "add_ln10_4_fu_242_p2");
    sc_trace(mVcdFile, mul_ln10_fu_252_p0, "mul_ln10_fu_252_p0");
    sc_trace(mVcdFile, mul_ln10_fu_252_p1, "mul_ln10_fu_252_p1");
    sc_trace(mVcdFile, mul_ln10_fu_252_p2, "mul_ln10_fu_252_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("matrix_mult.hdltvin.dat");
    mHdltvoutHandle.open("matrix_mult.hdltvout.dat");
}

matrix_mult::~matrix_mult() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void matrix_mult::thread_ap_clk_no_reset_() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        C_load_reg_94 = add_ln10_fu_258_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln7_fu_160_p2.read()))) {
        C_load_reg_94 = ap_const_lv32_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln7_fu_160_p2.read(), ap_const_lv1_1))) {
        i_0_reg_72 = i_reg_267.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_72 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln9_fu_186_p2.read(), ap_const_lv1_1))) {
        j_0_reg_83 = j_reg_281.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln6_fu_118_p2.read(), ap_const_lv1_0))) {
        j_0_reg_83 = ap_const_lv4_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        k_0_reg_107 = k_reg_299.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln7_fu_160_p2.read()))) {
        k_0_reg_107 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln7_fu_160_p2.read()))) {
        C_addr_reg_291 =  (sc_lv<7>) (zext_ln8_1_fu_181_p1.read());
        zext_ln8_reg_286 = zext_ln8_fu_172_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln6_fu_118_p2.read(), ap_const_lv1_0))) {
        add_ln10_1_reg_272 = add_ln10_1_fu_154_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_267 = i_fu_124_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        j_reg_281 = j_fu_166_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        k_reg_299 = k_fu_192_p2.read();
    }
}

void matrix_mult::thread_A_address0() {
    A_address0 =  (sc_lv<7>) (zext_ln10_3_fu_207_p1.read());
}

void matrix_mult::thread_A_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        A_ce0 = ap_const_logic_1;
    } else {
        A_ce0 = ap_const_logic_0;
    }
}

void matrix_mult::thread_B_address0() {
    B_address0 =  (sc_lv<7>) (zext_ln10_6_fu_247_p1.read());
}

void matrix_mult::thread_B_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        B_ce0 = ap_const_logic_1;
    } else {
        B_ce0 = ap_const_logic_0;
    }
}

void matrix_mult::thread_C_address0() {
    C_address0 = C_addr_reg_291.read();
}

void matrix_mult::thread_C_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        C_ce0 = ap_const_logic_1;
    } else {
        C_ce0 = ap_const_logic_0;
    }
}

void matrix_mult::thread_C_d0() {
    C_d0 = C_load_reg_94.read();
}

void matrix_mult::thread_C_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        C_we0 = ap_const_logic_1;
    } else {
        C_we0 = ap_const_logic_0;
    }
}

void matrix_mult::thread_add_ln10_1_fu_154_p2() {
    add_ln10_1_fu_154_p2 = (!zext_ln10_1_fu_150_p1.read().is_01() || !zext_ln10_fu_138_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln10_1_fu_150_p1.read()) + sc_biguint<8>(zext_ln10_fu_138_p1.read()));
}

void matrix_mult::thread_add_ln10_2_fu_202_p2() {
    add_ln10_2_fu_202_p2 = (!add_ln10_1_reg_272.read().is_01() || !zext_ln10_2_fu_198_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(add_ln10_1_reg_272.read()) + sc_biguint<8>(zext_ln10_2_fu_198_p1.read()));
}

void matrix_mult::thread_add_ln10_3_fu_236_p2() {
    add_ln10_3_fu_236_p2 = (!zext_ln10_5_fu_232_p1.read().is_01() || !zext_ln10_4_fu_220_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln10_5_fu_232_p1.read()) + sc_biguint<8>(zext_ln10_4_fu_220_p1.read()));
}

void matrix_mult::thread_add_ln10_4_fu_242_p2() {
    add_ln10_4_fu_242_p2 = (!add_ln10_3_fu_236_p2.read().is_01() || !zext_ln8_reg_286.read().is_01())? sc_lv<8>(): (sc_biguint<8>(add_ln10_3_fu_236_p2.read()) + sc_biguint<8>(zext_ln8_reg_286.read()));
}

void matrix_mult::thread_add_ln10_fu_258_p2() {
    add_ln10_fu_258_p2 = (!mul_ln10_fu_252_p2.read().is_01() || !C_load_reg_94.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln10_fu_252_p2.read()) + sc_biguint<32>(C_load_reg_94.read()));
}

void matrix_mult::thread_add_ln8_fu_176_p2() {
    add_ln8_fu_176_p2 = (!add_ln10_1_reg_272.read().is_01() || !zext_ln8_fu_172_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(add_ln10_1_reg_272.read()) + sc_biguint<8>(zext_ln8_fu_172_p1.read()));
}

void matrix_mult::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void matrix_mult::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void matrix_mult::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void matrix_mult::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void matrix_mult::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void matrix_mult::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln6_fu_118_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void matrix_mult::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void matrix_mult::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln6_fu_118_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void matrix_mult::thread_i_fu_124_p2() {
    i_fu_124_p2 = (!i_0_reg_72.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_0_reg_72.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void matrix_mult::thread_icmp_ln6_fu_118_p2() {
    icmp_ln6_fu_118_p2 = (!i_0_reg_72.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_72.read() == ap_const_lv4_A);
}

void matrix_mult::thread_icmp_ln7_fu_160_p2() {
    icmp_ln7_fu_160_p2 = (!j_0_reg_83.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(j_0_reg_83.read() == ap_const_lv4_A);
}

void matrix_mult::thread_icmp_ln9_fu_186_p2() {
    icmp_ln9_fu_186_p2 = (!k_0_reg_107.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(k_0_reg_107.read() == ap_const_lv4_A);
}

void matrix_mult::thread_j_fu_166_p2() {
    j_fu_166_p2 = (!j_0_reg_83.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(j_0_reg_83.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void matrix_mult::thread_k_fu_192_p2() {
    k_fu_192_p2 = (!k_0_reg_107.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(k_0_reg_107.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void matrix_mult::thread_mul_ln10_fu_252_p0() {
    mul_ln10_fu_252_p0 = B_q0.read();
}

void matrix_mult::thread_mul_ln10_fu_252_p1() {
    mul_ln10_fu_252_p1 = A_q0.read();
}

void matrix_mult::thread_mul_ln10_fu_252_p2() {
    mul_ln10_fu_252_p2 = (!mul_ln10_fu_252_p0.read().is_01() || !mul_ln10_fu_252_p1.read().is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln10_fu_252_p0.read()) * sc_bigint<32>(mul_ln10_fu_252_p1.read());
}

void matrix_mult::thread_tmp_1_fu_142_p3() {
    tmp_1_fu_142_p3 = esl_concat<4,1>(i_0_reg_72.read(), ap_const_lv1_0);
}

void matrix_mult::thread_tmp_2_fu_212_p3() {
    tmp_2_fu_212_p3 = esl_concat<4,3>(k_0_reg_107.read(), ap_const_lv3_0);
}

void matrix_mult::thread_tmp_3_fu_224_p3() {
    tmp_3_fu_224_p3 = esl_concat<4,1>(k_0_reg_107.read(), ap_const_lv1_0);
}

void matrix_mult::thread_tmp_fu_130_p3() {
    tmp_fu_130_p3 = esl_concat<4,3>(i_0_reg_72.read(), ap_const_lv3_0);
}

void matrix_mult::thread_zext_ln10_1_fu_150_p1() {
    zext_ln10_1_fu_150_p1 = esl_zext<8,5>(tmp_1_fu_142_p3.read());
}

void matrix_mult::thread_zext_ln10_2_fu_198_p1() {
    zext_ln10_2_fu_198_p1 = esl_zext<8,4>(k_0_reg_107.read());
}

void matrix_mult::thread_zext_ln10_3_fu_207_p1() {
    zext_ln10_3_fu_207_p1 = esl_zext<64,8>(add_ln10_2_fu_202_p2.read());
}

void matrix_mult::thread_zext_ln10_4_fu_220_p1() {
    zext_ln10_4_fu_220_p1 = esl_zext<8,7>(tmp_2_fu_212_p3.read());
}

void matrix_mult::thread_zext_ln10_5_fu_232_p1() {
    zext_ln10_5_fu_232_p1 = esl_zext<8,5>(tmp_3_fu_224_p3.read());
}

void matrix_mult::thread_zext_ln10_6_fu_247_p1() {
    zext_ln10_6_fu_247_p1 = esl_zext<64,8>(add_ln10_4_fu_242_p2.read());
}

void matrix_mult::thread_zext_ln10_fu_138_p1() {
    zext_ln10_fu_138_p1 = esl_zext<8,7>(tmp_fu_130_p3.read());
}

void matrix_mult::thread_zext_ln8_1_fu_181_p1() {
    zext_ln8_1_fu_181_p1 = esl_zext<64,8>(add_ln8_fu_176_p2.read());
}

void matrix_mult::thread_zext_ln8_fu_172_p1() {
    zext_ln8_fu_172_p1 = esl_zext<8,4>(j_0_reg_83.read());
}

void matrix_mult::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln6_fu_118_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln7_fu_160_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln9_fu_186_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        default : 
            ap_NS_fsm = "XXXXX";
            break;
    }
}

void matrix_mult::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"A_address0\" :  \"" << A_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"A_ce0\" :  \"" << A_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"A_q0\" :  \"" << A_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"B_address0\" :  \"" << B_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"B_ce0\" :  \"" << B_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"B_q0\" :  \"" << B_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"C_address0\" :  \"" << C_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"C_ce0\" :  \"" << C_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"C_we0\" :  \"" << C_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"C_d0\" :  \"" << C_d0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

