// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="dense_simple_dense_simple,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu13p-fsga2577-2-e,HLS_INPUT_CLOCK=25.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.542000,HLS_SYN_LAT=75,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=752,HLS_SYN_LUT=880,HLS_VERSION=2024_1}" *)

module dense_simple (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_address0,
        x_ce0,
        x_q0,
        x_address1,
        x_ce1,
        x_q1,
        w_address0,
        w_ce0,
        w_q0,
        w_address1,
        w_ce1,
        w_q1,
        y_address0,
        y_ce0,
        y_we0,
        y_d0
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] x_address0;
output   x_ce0;
input  [31:0] x_q0;
output  [3:0] x_address1;
output   x_ce1;
input  [31:0] x_q1;
output  [6:0] w_address0;
output   w_ce0;
input  [31:0] w_q0;
output  [6:0] w_address1;
output   w_ce1;
input  [31:0] w_q1;
output  [2:0] y_address0;
output   y_ce0;
output   y_we0;
output  [31:0] y_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] x_load_reg_245;
wire    ap_CS_fsm_state2;
reg   [31:0] x_load_1_reg_250;
reg   [31:0] x_load_2_reg_265;
wire    ap_CS_fsm_state3;
reg   [31:0] x_load_3_reg_270;
reg   [31:0] x_load_4_reg_285;
wire    ap_CS_fsm_state4;
reg   [31:0] x_load_5_reg_290;
reg   [31:0] x_load_6_reg_305;
wire    ap_CS_fsm_state5;
reg   [31:0] x_load_7_reg_310;
reg   [31:0] x_load_8_reg_325;
wire    ap_CS_fsm_state6;
reg   [31:0] x_load_9_reg_330;
reg   [31:0] x_load_10_reg_345;
wire    ap_CS_fsm_state7;
reg   [31:0] x_load_11_reg_350;
reg   [31:0] x_load_12_reg_365;
wire    ap_CS_fsm_state8;
reg   [31:0] x_load_13_reg_370;
reg   [31:0] x_load_14_reg_385;
wire    ap_CS_fsm_state9;
reg   [31:0] x_load_15_reg_390;
wire    grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_ap_start;
wire    grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_ap_done;
wire    grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_ap_idle;
wire    grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_ap_ready;
wire   [6:0] grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_w_address0;
wire    grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_w_ce0;
wire   [6:0] grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_w_address1;
wire    grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_w_ce1;
wire   [2:0] grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_y_address0;
wire    grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_y_ce0;
wire    grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_y_we0;
wire   [31:0] grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_y_d0;
reg    grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_ap_start_reg;
wire    ap_CS_fsm_state10;
reg    x_ce1_local;
reg   [3:0] x_address1_local;
reg    x_ce0_local;
reg   [3:0] x_address0_local;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_ap_start_reg = 1'b0;
end

dense_simple_dense_simple_Pipeline_VITIS_LOOP_8_1 grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_ap_start),
    .ap_done(grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_ap_done),
    .ap_idle(grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_ap_idle),
    .ap_ready(grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_ap_ready),
    .w_address0(grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_w_address0),
    .w_ce0(grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_w_ce0),
    .w_q0(w_q0),
    .w_address1(grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_w_address1),
    .w_ce1(grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_w_ce1),
    .w_q1(w_q1),
    .x_load_7(x_load_7_reg_310),
    .x_load_11(x_load_11_reg_350),
    .x_load_8(x_load_8_reg_325),
    .x_load_2(x_load_2_reg_265),
    .x_load_1(x_load_1_reg_250),
    .x_load_5(x_load_5_reg_290),
    .x_load_12(x_load_12_reg_365),
    .x_load_3(x_load_3_reg_270),
    .x_load_10(x_load_10_reg_345),
    .x_load_4(x_load_4_reg_285),
    .x_load_13(x_load_13_reg_370),
    .x_load_6(x_load_6_reg_305),
    .x_load(x_load_reg_245),
    .x_load_14(x_load_14_reg_385),
    .x_load_9(x_load_9_reg_330),
    .x_load_15(x_load_15_reg_390),
    .y_address0(grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_y_address0),
    .y_ce0(grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_y_ce0),
    .y_we0(grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_y_we0),
    .y_d0(grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_y_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_ap_start_reg <= 1'b1;
        end else if ((grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_ap_ready == 1'b1)) begin
            grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        x_load_10_reg_345 <= x_q1;
        x_load_11_reg_350 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        x_load_12_reg_365 <= x_q1;
        x_load_13_reg_370 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        x_load_14_reg_385 <= x_q1;
        x_load_15_reg_390 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        x_load_1_reg_250 <= x_q0;
        x_load_reg_245 <= x_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        x_load_2_reg_265 <= x_q1;
        x_load_3_reg_270 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        x_load_4_reg_285 <= x_q1;
        x_load_5_reg_290 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_load_6_reg_305 <= x_q1;
        x_load_7_reg_310 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        x_load_8_reg_325 <= x_q1;
        x_load_9_reg_330 <= x_q0;
    end
end

always @ (*) begin
    if ((grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        x_address0_local = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        x_address0_local = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        x_address0_local = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        x_address0_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        x_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        x_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        x_address0_local = 64'd1;
    end else begin
        x_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        x_address1_local = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        x_address1_local = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        x_address1_local = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        x_address1_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        x_address1_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        x_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        x_address1_local = 64'd0;
    end else begin
        x_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        x_ce0_local = 1'b1;
    end else begin
        x_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        x_ce1_local = 1'b1;
    end else begin
        x_ce1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_ap_start = grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_ap_start_reg;

assign w_address0 = grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_w_address0;

assign w_address1 = grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_w_address1;

assign w_ce0 = grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_w_ce0;

assign w_ce1 = grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_w_ce1;

assign x_address0 = x_address0_local;

assign x_address1 = x_address1_local;

assign x_ce0 = x_ce0_local;

assign x_ce1 = x_ce1_local;

assign y_address0 = grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_y_address0;

assign y_ce0 = grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_y_ce0;

assign y_d0 = grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_y_d0;

assign y_we0 = grp_dense_simple_Pipeline_VITIS_LOOP_8_1_fu_209_y_we0;

endmodule //dense_simple
